### PR TITLE
[WIP] Add manifest maintenance doc

### PR DESCRIPTION
**Pull request by tmjd**
## Description
This is the start of a doc to keep track of how we maintain, create, and update the manifests we keep for installing/deploying Calico in K8s.  We want to improve how we maintain, store, and present the manifests for deploying Calico and I think a first step to that is writing down what we currently do, this PR is an attempt at writing that down.

```release-note
None required
```

### CODE REVIEW

**Comment by tmjd** [comment]
One thing to note I put we should support at most 3 revisions of K8s and if that is right then we can start dropping support of K8s 1.5.

**Comment by emanic** [comment]
As per @ahrkrak I think that we still need to support 1.5, but not prior.

**Comment by tmjd** [comment]
From recent conversations I don't think it is still the case that we still support 1.5. Is that your understanding as well @emanic?

**Comment by emanic** [comment]
Yes, that's right @tmjd .

**Comment by tmjd** [comment]
The purpose of the document is to record what we are doing so we have agreement on how we handle manifest maintenance currently. I'm not trying to introduce new process or procedure, just get written down what we currently expect.  What I want from the document is to record what we expect so that when we need to create new manifests or make updates it does not require a discussion about what should be done.

This feeds into updates we have planned for Canal because I think it has been stated that we should handle Canal the same as the Calico manifests.

**Pull request closed without merging**
