### PR TITLE
docs: Add env CALICO_IPV6POOL_NAT_OUTGOING to calico-node for IPv6

### LINKED ISSUE #7183: The ip6tables SNAT(MASQUERADE) rule for pod IPv6 to outside world is missing
Hi!

I have 3 VMs in the same link layer, with the following IP address:
```
k8s-1: 192.168.0.2, fd00::2
k8s-2: 192.168.0.3, fd00::3
nginx: 192.168.0.4, fd00::4
```

I followed the document [Enable dual stack](https://projectcalico.docs.tigera.io/networking/ipv6#enable-dual-stack) to create a dual-stack K8S cluster on VM `k8s-1` and `k8s-2`, and the pod IPv6 subnet is ULA `fd01::/64`. I created a pod in the cluster, and then `ping` VM `nginx` IPv4 and IPv6 address. IPv4 worked as my expect, but there was no reply for IPv6!

Actually, there is no ip6tables MASQUERADE rule to outside on K8S node. In `nat` table, chain `POSTROUTING -> cali-POSTROUTING -> cali-nat-outgoing`, there is a MASQUERADE rule for ip4tables, but no rule in same position for ip6tables! The VM `nginx` will not reply the ICMPv6 request from the pod (with source fd01::xx), because there is no route for fd01::/64 on `nginx`.

After adding ip6tables MASQUERADE rule on K8S node, ping `nginx` IPv6 worked as my expect.
 
## Expected Behavior

The pod can communicate with the outside world over IPv6.

## Current Behavior

The pod can not actually.

## Possible Solution

Add ip6tables MASQUERADE rule on K8S node.

## Steps to Reproduce (for bugs)

1. Create dual-stack K8S cluster follow the document [kubeadm dual-stack support](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/dual-stack-support/). My kubeadm init command `kubeadm init --pod-network-cidr=10.17.0.0/16,fd01::/54 --service-cidr=10.112.0.0/16,fd01:0:0:400::/112`
2. Install calico CNI and enable dual-stack, follow the document [enable dual-stack](https://projectcalico.docs.tigera.io/networking/ipv6#enable-dual-stack)
3. Create a pod in dual-stack cluster
4. Ping outside world IPv6 address in the pod, for example `fd01::4`

## Your Environment

* Calico version
  v3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt):
  1.24.3
* Operating System and version:

```
OS:
  PRETTY_NAME="Ubuntu 22.04 LTS"
  NAME="Ubuntu"
  VERSION_ID="22.04"
  VERSION="22.04 (Jammy Jellyfish)"
  VERSION_CODENAME=jammy
  ID=ubuntu
  ID_LIKE=debian
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  UBUNTU_CODENAME=jammy
  
 Kernel:
   Linux virtink-01 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by carezkh**
## Related issues/PRs
fix #7183

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by mgleung** [comment]
@carezkh I think we may want to add an explanation of what `CALICO_IPV6POOL_NAT_OUTGOING` does in this case instead of just instructing users to set it since I think there are some cases where it might not be desirable to have this set.

**Comment by carezkh** [comment]
@mgleung Done.

**Comment by caseydavenport** [comment]
Do we want to add anything to the `operator tab` for this page?

Also, documentation has recently moved to github.com/tigera/docs, so I think we will need to re-open this PR over there.

CC @ctauchen

**Comment by carezkh** [comment]
@caseydavenport IIUC, There is no need to update `operator tab`, the field `natOutgoning` is `enabled` for default IPPool. And i'm glad to open this PR in github.com/tigera/docs.

**Comment by caseydavenport** [comment]
Closing in favor of https://github.com/tigera/docs/pull/464

**Pull request closed without merging**
