### PR TITLE
Documentation: Kind multi-node install

### PR DESCRIPTION
**Pull request by afshin-deriv**
Signed-off-by: Afshin Paydar <afshin.paydar@binary.com>

## Description
Documentation Update
Install Calico on Kind multi-node cluster

### CODE REVIEW

**Comment by ctauchen** [comment]
@afshinpaydar-binary Thanks for the contribution! We've added this PR to our agenda for an upcoming docs team meeting. We'll be in touch after we've had a chance to consider it.

**Comment by lwr20** [comment]
@ctauchen How did the docs team meeting go?  

FWIW, I can confirm that the contents of this doc are good (I've used kind to set up clusters like this many times)

I think the only questions are: 
- do you want this added to the docs at all? (I think its useful)
- are there any style changes needed?

**Review by caseydavenport — APPROVED** [review]

**Comment by ctauchen** [comment]
> 

@lwr20 I completely lost track of this one -- apologies @afshin-deriv. 

As for whether it's useful and belongs -- I'll defer to you and Casey.

It's well organized and written. We'll follow up with whatever style and formatting changes we need later.

**Comment by lwr20** [comment]
Casey's merged this already, so I assume it must have his blessing :)

**Pull request merged**
