### PR TITLE
Rev netlink to pick up RouteListIter

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

I made a PR to the upstream netlink repo that was just merged.  It changes the library's internal read loop to use an iterator, which avoid a lot of allocations (10% speedup + lower allocs in my benchmarks).  There's also a new, more efficient API but I'll tackle that once the dust settles on #8418 .

## Related issues/PRs

https://github.com/vishvananda/netlink/pull/940

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Felix now uses less CPU and memory when listing routes from the kernel.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by aaaaaaaalex — APPROVED** [review]
LGTM, ignoring CI failure :smile:

**Comment by fasaxc** [comment]
Converting to draft since the upstream repo has a critical bug that affects the commit I tried to rev to: https://github.com/vishvananda/netlink/issues/959

**Comment by fasaxc** [comment]
Bad commit was reverted again, my bad

**Comment by fasaxc** [comment]
@aaaaaaaalex CI fail is an nftables flake; it's with Casey.

**Pull request merged**
