### PR TITLE
Add search to docs.

### PR DESCRIPTION
**Pull request by djosborne**

### CODE REVIEW

**Comment by tomdee** [comment]
Looks great. Some questions before merging:

1. What CSE ID did you use? Who has access to it?
2. What actions need to be performed when we release? Can you add them to the RELEASING.md file?

**Comment by djosborne** [comment]
1. I created had a shared CSE business account created of which I am an admin. I added @robbrockbank as an owner as well since he is co-owner of this repo.
2. Addressed - I updated the RELEASING.md to include the steps.

**Comment by tomdee** [comment]
LGTM - we might want to consider using an XML file for config (I think that's an option) then we might even be able to template it and avoid needed to to log into CSE when we add a new version. If you think that's possible can you raise an issue to track it?

**Comment by djosborne** [comment]
@tomdee You can import / export XML files into the CSE console to configure it, but it doesn't seem like you can do it live on the site. GSCE does expose _some_ settings on the page, but not all. 

For example, there's a param called `DefaultToRefinement` that can be configured right from the page:
>Available only if refinements have been created in the Custom Search control panel. Specifies the default refinement label to display.

But it's description suggests that refinements themselves need to be configured in the control panel beforehand.

**Pull request merged**
