### PR TITLE
update the docs for libnetwork ifprefix option

### LINKED ISSUE #332: update calicoctl docs for Libnetowokr IFPREFIX
See https://github.com/projectcalico/calico-containers/pull/1390 for reference

### PR DESCRIPTION
**Pull request by gunjan5**
For PR https://github.com/projectcalico/calico-containers/pull/1390
Fixes #332

### CODE REVIEW

**Comment by caseydavenport** [comment]
Can't actually merge this to v2.0 since it doesn't exist in the beta.

**Comment by robbrockbank** [comment]
Yup if you can just undo the v2.0 change for now, that would be great :-)

**Comment by gunjan5** [comment]
ok fine! removed

**Comment by caseydavenport** [comment]
BTW you can un-remove that now.

**Comment by robbrockbank** [comment]
Yes, if you could unremove that would be great :-)


tee hee

**Comment by gunjan5** [comment]
un-remove what? 😉  
back to you

**Comment by gunjan5** [comment]
semaphore failure seems unrelated

**Comment by robbrockbank** [comment]
lgtm

**Pull request merged**
