### PR TITLE
Fix links in custom-resources.yaml manifest

### PR DESCRIPTION
**Pull request by krnowak**
These were 404.

### CODE REVIEW

**Comment by fasaxc** [comment]
:wave: and thanks for the PR.  I think those files are autogenerated from the `.go` files in the operator repo so they need to be updated there first.

**Comment by fasaxc** [comment]
Ah OK, right you are; I thought it was the CRDs you were editing bu it's the CRs.

**Comment by caseydavenport** [comment]
Sorry for the delay!

**Pull request merged**
