### PR TITLE
Fix default felix log levels

### PR DESCRIPTION
**Pull request by caseydavenport**
Looks like the default for all of these is actually INFO.

@fasaxc is this a docs bug or a Felix bug?

### CODE REVIEW

**Comment by ozdanborne** [comment]
ping @fasaxc

**Comment by ozdanborne** [comment]
@caseydavenport What is the next action on this PR?

**Comment by caseydavenport** [comment]
There is an outstanding question that needs to be answered by @fasaxc, and it needs review / approval.

**Comment by fasaxc** [comment]
Code definitely says `INFO` for all three.  Hmm, I think that's wrong, think we used to only do ERROR to syslog, for example.  Good defaults depend on environment though.  Presumable we want to log INFO to screen in container land?

**Comment by caseydavenport** [comment]
@fasaxc yeah, we usually want to do INFO to screen for containers.

It's useful to have that as the default in k8s for the daemonset install so we can mount in a file and override it for a particular node - if we have to set an env var then the file based config won't override that.

**Comment by caseydavenport** [comment]
I'm going to merge this for now since this is the default.  We can address if we want to change the code later.

**Pull request merged**
