### PR TITLE
Release notes and table for Calico v1.6.1

### PR DESCRIPTION
**Pull request by gunjan5**

### CODE REVIEW

**Comment by caseydavenport** [comment]
I think you're missing the update of all the v1.6 docs to point at the new versions.

**Comment by gunjan5** [comment]
@caseydavenport done. PTAL

**Comment by gunjan5** [comment]
CI failures seem to be from docs.mirantis.com/openstack/fuel/fuel-6.1/user-guide.html which is not over https apparently but works over http

**Comment by caseydavenport** [comment]
@gunjan5 we should fix up the broken link then

**Comment by gunjan5** [comment]
So I did some more QA on this to make sure.
- Started the Vagrant demo VMs, calicoctl reports v0.23.1, it starts calico/node:v0.23.1
- did a kubeadm hosted install
- ran through simple policy demo
Things seem to work fine

As far as the mirantis links go, even when I move to `http` browsers still throw security warning and I'm guessing that's why CI also still fails, not sure there's much we can do about it.

**Comment by caseydavenport** [comment]
Docs changes LGTM.

Not sure what we can do about the broken links... @neiljerram are those Mirantis links still valid?

**Comment by neiljerram** [comment]
@caseydavenport Well, on the Mirantis/Fuel info overall...

- I can't remember how the available Fuel plugin versions map through onto versions of Calico/Felix/networking-calico.  It's quite likely wrong, though, to be including this Fuel-information in each version-specific subtree of the Calico docs.  It feels like it belongs more in a Calico-version-independent place.  Or perhaps at http://docs.openstack.org/developer/networking-calico/ instead of http://docs.projectcalico.org/.

- Also we haven't done any Fuel work or testing ourselves now for quite a while - so perhaps we should just drop this page from the current 'master' tree, so that it does not appear in future releases.  (Unless we actually work on it again, of course.)

So possibly we should just delete this, or possibly move it elsewhere - thoughts?  (Also @fasaxc )

**Comment by gunjan5** [comment]
@caseydavenport @neiljerram seems like this is docs restructuring discussion. We shouldn't hold up this PR for it. Can this be a separate issue/PR?

**Comment by neiljerram** [comment]
@gunjan5 Fine with me!

**Comment by caseydavenport** [comment]
I think we need to do something to fix the tests before we merge.  That could be removing the link and adding an issue to put it back, or finding another suitable link, or something else.

**Comment by caseydavenport** [comment]
@gunjan5 back to you to figure out what to do about the tests and then merge.

**Comment by gunjan5** [comment]
@caseydavenport seems like those mirantis links are working fine now, but test is failing because of the openstack juno (EOL'd) links

**Comment by caseydavenport** [comment]
@gunjan5 OK.  Those are being fixed in another PR, so let's merge this.

**Pull request merged**
