### PR TITLE
Remove generated files from felix's list of files to clean.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

The overzealous clean often catches people out and it's causing a build breakage over in the enterprise builds.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by neiljerram — APPROVED** [review]
LGTM - although with a possibly important caveat that I never use `make clean`!

**Comment by fasaxc** [comment]
I usually avoid `make clean` because it blows away these files :laughing:

**Pull request merged**
