### PR TITLE
Incorrect comment in kubeadm calico.yaml

### PR DESCRIPTION
**Pull request by anirban37**
## Description

Fixed incorrect comments in 
-->3.0-->kubeadm-->1.6-->calico.yaml
-->2.6-->kubeadm-->1.6-->calico.yaml
-->master-->kubeadm-->1.6-->calico.yaml

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@anirban37 Could you also update this in the `master` directory so that this gets persisted for future releases? thanks!

**Comment by anirban37** [comment]
Done .. updated the same on master directory :)

**Comment by emanic** [comment]
All right, great @anirban37 ... now if you can just sign our CLA, we should be good to go. Looks like you may need to configure your command-line git with your email address https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by neiljerram** [comment]
@anirban37 Would you be able to sign our CLA for this contribution?  I'm happy to finish the rest - i.e. rebasing to handle conflicts, and squashing - but we need your CLA first to be able to use this at all.  Thanks!

**Comment by anirban37** [comment]
@neiljerram I already signed

**Comment by ozdanborne** [comment]
@anirban37 it looks the email on the commit isn't registered with your github account, so github / clabot isn't able to match it to you. Can you amend the commit so that it includes a valid email?

**Comment by neiljerram** [comment]
Hey @anirban37 - I was just taking another look at this, because I thought I might be able to fix up your commit email myself so that it matches what you put in your CLA.  But it appears that the commit diff is no longer available through Git operations (as described in the "or view command line instructions" link, next to the "Merge pull request"); specifically, `curl -L https://github.com/projectcalico/calico/pull/1284.patch` just gives
```
Sorry, this diff is unavailable.
```
I also noted that it says, above: **anirban37** wants to merge 2 commits into `projectcalico:master` from `unknown repository`.  That `unknown repository` is odd, and I guess it might be related to the unavailability of the diff.

So overall I'm afraid there's really nothing that we can do with this PR.  I think the best way forward, if you'd like to do this, would be to redo the change and PR from scratch again, using a branch in your fork at https://github.com/anirban37/calico, and making sure that your Git user.email is set to the same address that you put in your CLA.  So I'll close this PR now, and look forward to seeing that replacement from you soon.

**Pull request closed without merging**
