### PR TITLE
Rev python-etcd to 0.4.2.

### PR DESCRIPTION
**Pull request by fasaxc**
Remove dependency on custom build of python-etcd now that our patches are upstreamed.

### CODE REVIEW

**Comment by matthewdupre** [comment]
tox.ini needs updating too.  It specifies a commit id for python-etcd.

**Comment by fasaxc** [comment]
Done

**Comment by fasaxc** [comment]
retest this please

**Comment by matthewdupre** [comment]
retest this please

**Comment by matthewdupre** [comment]
retest this please

**Comment by fasaxc** [comment]
Build timed out, retest this please

**Comment by matthewdupre** [comment]
retest this please

**Comment by fasaxc** [comment]
Hmm, chef install failed.  Not sure we have time to dig into that before 1.2.0 so let's bump this patch to the next release.

**Comment by matthewdupre** [comment]
Turns out EL7 setuptools is so old that +s get treated as -s, which sort differently.  I'm going to back this out (but still tell people to use the latest and greatest).  It's a bit of a shame really: we can clean it all up when we get to 0.4.3.

**Pull request merged**
