### PR TITLE
move helm infra to branch-per-version

### PR DESCRIPTION
**Pull request by ozdanborne**
## Description

De-versions helm directories and functions.

Basically,
```
mv _includes/master/charts _includes/charts
mv _plugins/master/* _plugins/
```

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit a91d3da39dd094449e75f62576c7d611ade3a3f5

https://deploy-preview-3120--calico.netlify.com

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit abfe84b7f340675b089b61564d0543dc5c22e5cd

https://deploy-preview-3120--calico.netlify.com

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit df41f37144f0f3231c543cd7cd378ef6c87f9beb

https://deploy-preview-3120--calico.netlify.com

**Comment by tmjd** [comment]
I don't see how it would be related but looking at 
https://deploy-preview-3120--calico.netlify.com/master/getting-started/kubernetes/installation/calico
shows
`https://deploy-preview-3120--calico.netlify.com/master/manifests/calico-etcd.yaml%20-o%20calico.yaml`

**Comment by ozdanborne** [comment]
Nice spot. Unrelated, from #3115 . I'll do a follow-up PR to fix that, trying not to conflate commits & merges so that the pull from OS to Enterprise is easier

**Pull request merged**
