### PR TITLE
Extend kernel dependencies in v3.10 doc

### PR DESCRIPTION
**Pull request by mhmxs**
## Description

Not all of the Kernel dependencies were mentioned in the documentation.

## Related issues/PRs
partly fixes https://github.com/projectcalico/calicoctl/issues/1444

## Todos

- [ ] Backport to older versions

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit a1b67bd57e3ec6dce6f7bb56f51ea088b77ca67b

https://deploy-preview-3076--calico.netlify.com

**Comment by tmjd** [comment]
What is your thinking around the separate Calico and Felix list?
I think it should be one list and not try to identify what modules are required for any specific components. I also think it is unclear what is meant by Calico as I would normally assume that Calico includes Felix.
@fasaxc This list looks right to me but you would know much better than me, would you take a look please?

**Comment by fasaxc** [comment]
Agreed, felix is the only component that touches the dataplane so it's really just one list.

**Comment by mhmxs** [comment]
Thank you i updated the PR to contain only one list

**Pull request merged**
