### PR TITLE
Add enPxxx support to BPFDataIfacePattern

### PR DESCRIPTION
**Pull request by TrevorTaoARM**
## Description
For the Linux network device naming rules talked in [0],[1]: 
prefix [Pdomain] pbus sdevice [ffunction] [nphys_port_name | ddev_port]

The domain is omitted if it's 0 and the function is only present if it's a multi-function device. But for some network devices and/or Linux system, the domain is non-zero, so the pattern would be "enPxxxxxx".

On the other side, from the real case showed in our server, the ethernet interface name like "enP1p1s0f1" is valid as a normal data interface.

Now we lack this pattern in BPFDataIfacePattern, so for the bpf's ifstate map, this interface would be skipped as:

felix/bpf_ep_mgr.go 516: Ignoring interface that's neither data nor workload. update=&intdataplane.ifaceUpdate{Name:"enP1p1s0f1", State:"up", Index:4}

This lack would affect the normal work of eBPF communication since it would lack in the eBPF ifstate map which would be used in cali_iface_lookup_elem(&ifindex)
This PR is also part of the fix for the issue of:
https://github.com/projectcalico/calico/issues/6392

[0] https://utcc.utoronto.ca/~cks/space/blog/linux/UdevNetworkDeviceNaming [1] https://www.freedesktop.org/software/systemd/man/systemd.net-naming-scheme.html

Signed-off-by: trevor tao <trevor.tao@arm.com>

## Related issues/PRs
https://github.com/projectcalico/calico/issues/6392

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
ebpf: Include enPxxxxxx in the default BPFDataIfacePattern
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by tomastigera — APPROVED** [review]
Thanks!

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Pull request merged**
