### PR TITLE
Automated cherry pick of #5136: Removed form from footer navbar

### PR DESCRIPTION
**Pull request by bcreane**
Cherry pick of #5136 on release-v3.21.

#5136: Removed form from footer navbar

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by penkeysuresh — APPROVED** [review]
lgtm

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
