### PR TITLE
Do not include gobgp binary in calico-node

### PR DESCRIPTION
**Pull request by toshiiw**
calico-bgp-daemon has all the functionality and gobgpd isn't executed.

### CODE REVIEW

**Comment by gunjan5** [comment]
I've tested on my setup this and it works fine.
@toshiiw can you squash?

**Comment by toshiiw** [comment]
Hi @gunjan5 I rebased the patch but I'm not sure this is what you wanted.
Please let me know if I need to do some action on this.

**Comment by toshiiw** [comment]
semaphoreci failed because of transient connection failure to en.wikipedia.org, it seems.

**Comment by tmjd** [comment]
I think maybe you did a merge instead of a squash but yeah that isn't what @gunjan5 was looking for. 
It seems like you may be new to squashing with git, so you may want to make a backup branch of the one you are working on before continuing on, since you will be rewriting the history in your branch.
Checkout https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history it may help understand what gunjan5 was requesting.
The command you will need is `git rebase -i master` (assuming you originally branched off a local master branch).  This will give you the option to squash (combine) the commits in your branch since you forked off of master.  At that link above take a look at the section "Squash commits together" for how to make the edits to squash your commits.
After that you can push your changes but since you have pushed these changes to your fork before you will need to add the `-f` to force rewriting the branch history.

I kicked off a rebuild of the job in semaphoreci and it passed as you can probably see.

**Comment by gunjan5** [comment]
@toshiiw yeah, since this is only a few lines change it might be easier for you to create a new PR (after syncing your fork with upstream), and closing this, unless you can somehow revert based on what @tmjd said

**Comment by toshiiw** [comment]
Yes I'm not very familiar with github workflows. Maybe I shouldn't have clicked on "Rebase" button on github earlier. Thanks @tmjd @gunjan5.

Created https://github.com/projectcalico/calico/pull/972

**Comment by tmjd** [comment]
:smile: Yeah the Rebase button doesn't seem to do nice things.

**Pull request closed without merging**
