### PR TITLE
Set preserveUnknownFields to false in order to allow updating from th…

### PR DESCRIPTION
**Pull request by freecaykes**
## Description

Manual set of preserveUnknownFields to False in the generated CRDs in order to allow updating from the v1beta1 to the v1 API

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by caseydavenport** [comment]
Don't think the tests that are failing are relevant, so going to merge this.

**Comment by avorima** [comment]
@caseydavenport can this be cherry-picked onto the 3.23 branch for a patch release? Or what do you think is the ETA for 3.24?

**Comment by caseydavenport** [comment]
v3.24 is targeted for mid-August. I think this is also a cherry-pick candidate for v3.23

**Pull request merged**
