### PR TITLE
[WIP] Cleanup Calico/Vpp docs for release v3.25

### PR DESCRIPTION
**Pull request by onong**
## Description

Docs cleanup for release v3.25

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by caseydavenport** [comment]
CC @ctauchen

**Comment by ctauchen** [comment]
@onong Thanks for your contribution. You've caught us in the middle of migrating our docs source code and website. This repository is no longer accepting submissions. (We're about to delete the docs entirely: https://github.com/projectcalico/calico/pull/7204).

If you'd like, you can resubmit your changes to [our new docs repo](github.com/tigera/docs).

Sorry about the confusion.

**Comment by onong** [comment]
> @onong Thanks for your contribution. You've caught us in the middle of migrating our docs source code and website. This repository is no longer accepting submissions. (We're about to delete the docs entirely: #7204).
> 
> If you'd like, you can resubmit your changes to [our new docs repo](github.com/tigera/docs). I'm happy to help.
> 
> Sorry about the confusion.

Hi @ctauchen, thank you for the heads-up. I tried github.com/tigera/docs but I do not seem to have permissions:

> $ git push --dry-run
> ERROR: Permission to tigera/docs.git denied to onong.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> $

Could you please grant me the permissions?

**Comment by lwr20** [comment]
@onong like most OSS repos, the usual way to interact is to fork the repo, make your changes in the fork, then raise a PR to upstream.

**Comment by onong** [comment]
@lwr20 thanks, I keep on forgetting that :)

**Comment by ctauchen** [comment]
Fixes merged here: https://github.com/tigera/docs/pull/272

Closing this PR.

**Pull request closed without merging**
