### PR TITLE
Merge 1.2.2 release branch back into master

### PR DESCRIPTION
**Pull request by matthewdupre**

### CODE REVIEW

**Comment by matthewdupre** [comment]
I'll rebase it.

**Comment by matthewdupre** [comment]
Required check on the rebase: ensure that /sys/class/net/<interface_name> exists on Alpine Linux.

**Comment by matthewdupre** [comment]
@MatMeredith to review plugin related conflicts.

@fasaxc for others.

**Comment by matthewdupre** [comment]
I'm told @plwhite has been trying master on Alpine, so that covers the sys/class/net interface exists fix.

**Comment by matthewdupre** [comment]
retest this please

**Comment by matthewdupre** [comment]
retest this please

**Comment by fasaxc** [comment]
UTs are not passing after the naive merge, waiting on @MatMeredith to resolve.

**Comment by MatMeredith** [comment]
Latest changes merged from master, merge issues fixed and UTs now passing.   Back to @matthewdupre?

**Comment by matthewdupre** [comment]
calicotest.openstack.test_interfaces.TestMultipleInterfacesSecGroups has failed.

**Comment by fasaxc** [comment]
Build 216 failed due to a StaleDataError in the neutron plugin, which is a known issue in the neutron driver.

**Comment by matthewdupre** [comment]
OK - that's a WIP in the networking-calico repo.  Other tests were fine, so merging.

**Pull request merged**
