### PR TITLE
fix k8s policy-only toleration for master node

### PR DESCRIPTION
**Pull request by dtzar**
## Description

The daemonset doesn't apply to the master node and hence the master node network doesn't become ready when these two values aren't present - at least in my testing on a 1.7.5 and 1.8.0 cluster.

These values seem to be missing on previous versions and in different places, so might want or need to retrofit the yaml files for different installation options.  Just initiating this PR to get the conversation started.

### CODE REVIEW

**Comment by ozdanborne** [comment]
[According to the k8s docs](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/), the operator defaults to `Equal` if not specified. So specifying it looks fine to me.

For the value, [kubeadm sets it to an empty string](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/). I think that is the default as well.

Can you dump `kubectl get nodes -o yaml` so I can take a look at the taint on your cluster? That will help determine the taints that exist in ACS.

**Comment by caseydavenport** [comment]
FWIW this is what exists on the latest kubeadm:

```yaml
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    timeAdded: null
```

That's also what I understood the convention to be.

**Comment by dtzar** [comment]
yes, I believe the problem is when you deploy a K8s cluster _not_ using `kubeadm` the value does not get set.

**Comment by tmjd** [comment]
Thank you for pointing this issue out @dtzar and having a go at a fix.

What is the next step for this PR? I'm thinking this one should be closed as I think the fix should be to document that the tolerations in the manifests need to match the taints on the master, with perhaps a note that the manifests were written using kubeadm.  Actually even if we merge this PR we should document that requirement, see #1164.

**Comment by dtzar** [comment]
I don't believe this PR is a toleration/taints problem with the specific cluster deployment, although I agree with implementing your 1164 because it might be a problem for some deployments.  

I believe the solution should be to simply modify the places where the tolerations are present to have at least the `value: "true"` field present or both lines (in the event that there actually is a problem with the `Operator: Equal` isn't actually the default or take effect for whatever the reason with K8s).

**Comment by tmjd** [comment]
I just wanted to follow up, though I'm assuming since you closed the PR @dtzar that maybe you tested or reconsidered the taints and tolerations. I setup a k8s v1.8 cluster, deployed with kubeadm, and tried installing https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml though with the addition of `operator` and `value` as had been suggested and my calico-node pod was not deployed to my master, after removing those and applying my manifest then it was deployed to my master.

**Comment by dtzar** [comment]
I think I found out why it was this way for ACS-Engine.. Due to this taint put on the master node:
```
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      timeAdded: null
      value: "true"
```

**Pull request closed without merging**
