### PR TITLE
1.2.1

### PR DESCRIPTION
**Pull request by matthewdupre**
Merge 1.2.1 bugfix release branch back into master

### CODE REVIEW

**Comment by matthewdupre** [comment]
OK, I've done a rebase, but I'm not 100% confident in the ipset conflict resolution, so I want to get test runs done.

Also, let's never create a branch with the same name as the tag that needs to go on it; git didn't like it much.

**Comment by matthewdupre** [comment]
@fasaxc: could you please confirm the conflict resolution looks good?

**Comment by neiljerram** [comment]
@matthewdupre - I'm sorry, I had a look at the merge commit here, but it's very difficult for me to be sure if the resolutions are correct.  I think it will be much better for @fasaxc to look if he can spare a moment.  Anyway, I don't believe we lose anything by waiting a little longer, except for testing the merge in our ongoing testing; at least, any later changes in master can be merged independently of what you've already done.

@fasaxc - when you look at this, recommend looking at 6a9615b0b4 in gitk as well as in the GitHub view, as gitk will allow you to focus on just the conflicts.

**Comment by fasaxc** [comment]
@matthewdupre what do you mean that you rebased?  I'd expect a proper merge for a release branch reintegration.

**Comment by fasaxc** [comment]
I fixed up the conflicts under #905

**Comment by matthewdupre** [comment]
(Sorry yes, it was a merge not a rebase)

**Pull request closed without merging**
