### PR TITLE
Automated cherry pick of #4263: update enterprise trial url

### PR DESCRIPTION
**Pull request by bcreane**
Cherry pick of #4263 on release-v3.16.

#4263: update enterprise trial url

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 2637d473c64216257e86a1d026efa7751f6017cc

https://deploy-preview-4265--calico.netlify.app

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by lmm — APPROVED** [review]

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
