### PR TITLE
Added missing Openshift link

### PR DESCRIPTION
**Pull request by ToroNZ**
## Description

Added missing Openshift link

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by emanic** [comment]
This is really great @ToroNZ . The only issue is that the link does not seem to work correctly. However, we are missing this so if you can add a link that passes `htmlproofer` it will be nice to merge this.

**Comment by ToroNZ** [comment]
@emanic - Hopefully I've done it properly now :). Built it locally in my machine and seems to be working as expected. Cheers

**Comment by emanic** [comment]
Great thank you @ToroNZ ... any chance you could squash your commits, we would love to merge this 👍

**Comment by ToroNZ** [comment]
Please refer to #1522

**Pull request closed without merging**
