### PR TITLE
[WiP] Use a Makefile include to avoid recalculating versions on every run.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

I think this is the trick that we need to avoid recalculating the versions every time.

## Todos

- [ ] Improve the write-out of the versions file (echos with nested `$(shell...)` seems a bit long-winded)
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by fasaxc** [comment]
Ugh, fails on semaphore due to several targets re-execing the makefile in go-build with a different versions file.

**Comment by bcreane** [comment]
Does only removing the specific `versions.*.mk` associated with this invocation of make address the read-only filesystem error, e.g. `rm -f versions.$(RELEASE_STREAM).mk`.

Also it looks like the `$info()` statements are no longer reporting the version. I had a fix which @neiljerram and I were discussing which moved the version reporting from an $info which I think is evaluated in the first pass to the second pass. We might need to do something similar to get version reporting working if we use this `include versions*.mk` approach. See https://github.com/bcreane/calico/blob/dd54f28df6bfcbc926e848ed491555af6d9586df/calico_node/Makefile#L667

**Comment by fasaxc** [comment]
Not sure anyone should be reviewing this until I fix it up to run on semaphore...

**Comment by fasaxc** [comment]
Deleting all the versions files is intended.  It's a bit of a hack to make sure that we don't accumulate them after a few runs at different versions.  I can't just use a single filename because then make won't pick up when we switch branches.

**Comment by caseydavenport** [comment]
@fasaxc is this still a WIP? What does this buy us? Faster rebuilds?

**Comment by fasaxc** [comment]
@caseydavenport it speeds up the build a lot if you don't have the `yaml` command on your path but it's currently broken for the targets that semaphore uses due to the way they call back into the makefile.

**Comment by fasaxc** [comment]
(It also illustrates a general technique for managing complex or awkward to express dependencies in make.  You can import a makefile and then remake that imported file, triggering a recalculation of the deps.)

**Comment by caseydavenport** [comment]
To be honest, this PR scares me a bit because it feels super easy to build the wrong thing and not realize it, because the versions for a given release stream change fairly regularly. If we're careful about cleaning them up then I suppose it's OK, but still scary.

I've not personally had a problem with build speed in this repo, but I suppose we can continue with it if we can address the semaphore build stuff and we're confident we won't end up with releases with the wrong content in them... I'm still kinda hesitant...

**Comment by fasaxc** [comment]
@caseydavenport The intent was to rebuild the new versions makefile whenever the versions.yaml changes so that shouldn't be an issue.  I'm going to close this for now; the extra complexity in the targets semaphore uses makes it awkward to fix up.

**Pull request closed without merging**
