### PR TITLE
New Theme

### PR DESCRIPTION
**Pull request by djosborne**
Custom code for this PR which needs review
- `_layouts/docwithnav.html`
- `_includes/sidebar.html`
- `css/sidebar.scss`
- `css/style.scss`
- `js/script.js`

All other changes in this PR are either removal of files from the old theme, or addition of static files from the new theme (i.e. not written by us).

### CODE REVIEW

**Comment by djosborne** [comment]
- title at top and subtitle were removed. make sure its clean and what we wanted
- remove other k8s leftover theme files
- consolidate css directories
  - cleaner split of custom vs copied code
- list of custom files for reviewer
- remove custom getting started html page

**Comment by djosborne** [comment]
- [ ] Sidebar entries with parenthesis aren't expanding correctly.

**Comment by robbrockbank** [comment]
I think this looks much much better  - once passing semaphore and rebased on the latest code I'd be happy with this going in - and we can make further tweaks later on.

Does this work ok on mobile, did the old theme work ok on mobile?

**Comment by gunjan5** [comment]
Looks really good!!  Wanted to add a few things:
We should:
- make the table header a dark color (like in the old theme)
- alternate row in the table to be different color 
- when you clock on the hyperlinks they don't change color (usually it's blue to purple when the link is already visited)
- Code block (like a yaml for example) looks different (not red) like in most markdowns

Everything else looks dope!

**Pull request merged**
