### PR TITLE
Implements canonical tag with ability to define exceptions

### PR DESCRIPTION
**Pull request by emanic**
## Description

- Adds canonical tag to docwithnav.html that uses 'latest' directory
- Passes local htmlproofer
- Includes ability to define exceptions to the tag for deleted, renamed, and 404 pages
- Adds metadata to pages which are not present in 'latest'
- Incidentally adds validation for latest redirects

*Note*: Some of the no_canonicals can be removed when https://github.com/projectcalico/calico/pull/1202 is merged

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by ozdanborne** [comment]
Really nice indeed. Code-wise, LGTM. But I think we need to update our docs developer-docs with  information on when people will need to set this.

**Comment by emanic** [comment]
Thanks @ozdanborne 😄  You are right, I need to update the contributing docs MD file to discuss this. Will do in separate PR....

**Comment by ozdanborne** [comment]
Whoops, looks like it needs a rebase since I merged another PR :stuck_out_tongue:

**Comment by emanic** [comment]
Cool thanks!! 😄 I just removed a few canonical tags from the k8s quickstarts and am running htmlproofer locally to make sure, then will squash the commits and merge it.

**Pull request merged**
