### PR TITLE
Switch to 'info' level logging for policy-only calico manifest

### LINKED ISSUE #575: Felix debug logs turned on in calico.yaml
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/k8s-backend/calico.yaml
has
```
            - name: FELIX_LOGSEVERITYSCREEN
              value: "debug"
```
in the calico-node section.  Should this be set in a production system?

### PR DESCRIPTION
**Pull request by heschlie**
## Description

Fixes #575 

Changed CNI log level to `info` from `debug` in kubernetes-datastore manifests.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by bcreane** [comment]
lgtm!

**Comment by caseydavenport** [comment]
@heschlie @bcreane we really should not be changing values in the manifests for past releases.

This is good to do but please only for `master/` and _maybe_ the latest release (v2.5).

**Comment by heschlie** [comment]
Reverted the changes to apply only to the master manifests.

**Comment by bcreane** [comment]
hey @caseydavenport - with respect to your comment:

> we really should not be changing values in the manifests for past releases.

I think you're right that even low risk, but "nice to have" changes like this should not be back ported. To state the obvious: only issues that break use of older versions of manifests should be back ported.

**Pull request merged**
