### PR TITLE
Do not require a DHCP agent on the target compute host

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by neiljerram** [comment]
@fasaxc please could you review?

**Comment by neiljerram** [comment]
retest this please

**Comment by fasaxc** [comment]
retest this please

**Comment by alexwlchan** [comment]
Looks like this actually passed FVs, but my Jenkins clone did some meddling with GitHub PRs yesterday to give you a red cross. :-(

**Comment by fasaxc** [comment]
@neiljerram Feel free to merge this at the appropriate point for your testing

**Comment by neiljerram** [comment]
Thanks @fasaxc, I'll do that now, as it has no down side and may simplify Dave's future testing cycles.

**Pull request merged**
