### PR TITLE
Update manifests to work for node role label change

### PR DESCRIPTION
**Pull request by mgleung**
## Description

With K8s 1.24, the old node label of `master` is phased out. These changes to the manifests and docs should keep the manifests up to date with the new node label `control-plane`.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]

**Comment by caseydavenport** [comment]
We can probably remove the "master" label altogether - do you know when the control-plane label was introduced?

**Comment by mgleung** [comment]
From what I can tell it was introduced in K8s 1.20 so we might be fine with removal at this point (I need to check all the different versions of K8s we check against).

**Comment by mazdakn** [comment]
@caseydavenport do we still need this PR or shall we close it?

**Comment by caseydavenport** [comment]
@mazdakn the big picture is yes, we need to replace "master" with "control-plane" wherever it appears.

This particular PR is very out of date though, so probably worth closing it.

**Pull request closed without merging**
