### PR TITLE
Fix docs saying that serviceCluster/ExternalIPs are IPv4 only

### PR DESCRIPTION
**Pull request by neiljerram**
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by neiljerram** [comment]
Related validation PR: https://github.com/projectcalico/libcalico-go/pull/1321

**Comment by caseydavenport** [comment]
Does this require changes to confd templates? IIRC the limitation was in the templates rather than libcalico data model (but I could be misremembering, or maybe we've fixed it since then!)

**Comment by neiljerram** [comment]
@caseydavenport I had the same uncertainty in my mind, but then I remembered we did a whole bunch of work to extend service advertisement to IPv6; e.g. https://github.com/projectcalico/node/blob/master/tests/k8st/tests/test_bgp_advert_v6.py

Unless I'm still forgetting some other nuance .... ?

**Comment by caseydavenport** [comment]
Great!

**Review by caseydavenport — APPROVED** [review]

**Pull request merged**
