### PR TITLE
Move node-typha.yaml -> node.yaml

### PR DESCRIPTION
**Pull request by caseydavenport**
This manifest was incorrectly named as "typha" even though it is valid
independent of whether or not typha is in use.

Also move the KDD mode manifest to the top to match other guides.

- [ ] Tests
- [ ] Documentation
- [ ] Release note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 94a2b4c8b5d0e7e2673867f60ad7ed3ab3426f63

https://deploy-preview-2571--calico.netlify.com

**Comment by neiljerram** [comment]
Are you sure there aren't external references to the old name, which this change will break?

(Thought triggered by thinking of Henry's test script for installing and testing DNS policy in an EKS cluster, which uses a YAML named calico-typha.yaml.)

**Comment by caseydavenport** [comment]
@neiljerram I haven't changed the location for any released versions, just v3.7 and master. There may be external references to this manifest, but I'm not worried about breaking them if they are targeting unreleased code.

The currently released versions are actually different already, but I left them as-is. For example:

v3.6:
https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/manifests/app-layer-policy/kubernetes-datastore/calico-networking/calico-node.yaml

v3.7 (after this PR):
https://docs.projectcalico.org/v3.7/manifests/alp/node.yaml

**Comment by neiljerram** [comment]
Ok that sounds fine then; thanks for considering my paranoia!

**Pull request merged**
