### PR TITLE
Parameterize the build image hub organization name

### PR DESCRIPTION
**Pull request by jose-bigio**
Signed-off-by: jose-bigio <jose.bigio@docker.com>

## Description
 
Parameterize the organization name for calico.

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by tmjd** [comment]
LGTM.
@caseydavenport do we want this to be a standard thing?  (Note this is against the release-v3.0 branch)
If we do want to standardize on that then I think we should make the change in the base Makefile (docs), in the master branch, and in the calico/node repo master branch.

**Comment by jose-bigio** [comment]
Thanks for the review @tmjd to provide a little more context this would be desirable for something like s390x builds since the calico Docker hub repo currently doesn't have an s390x go-build image. 

Nonetheless, it is possible to override the entire CALICO_BUILD variable as opposed to part of it, but this makes it less likely for custom builds to be aligned with what Project Calico is doing (or at least could involve more effort in aligning). 

Another point is that the variable is: 

```
$(BUILD_IMAGE_ORG)/go-build$(ARCHTAG):$(GO_BUILD_VER)
```

but in hub the naming seems something more like:

```
$(BUILD_IMAGE_ORG)/go-build:$(GO_BUILD_VER)$(ARCHTAG)
```

**Comment by jose-bigio** [comment]
@caseydavenport  would it be okay if I changed this: 

```
CALICO_BUILD?=$(BUILD_IMAGE_ORG)/go-build$(ARCHTAG):$(GO_BUILD_VER)
```

to 

```
CALICO_BUILD?=$(BUILD_IMAGE_ORG)/go-build:$(GO_BUILD_VER)$(ARCHTAG)
```
(or any configuration that puts the architecture after the colon instead of before)
?


The current version indicates that there would be separate hub repos for `go-build` images for different architectures.

**Comment by tmjd** [comment]
@fasaxc since you've been reviewing the multi-arch changes, do you have any thoughts or guidance here?

**Comment by fasaxc** [comment]
@jose-bigio i think the main thing that we need to maintain for release branches is that we don't change anything that's already working.  So, I'd be OK with having a special case for s390x if that is required in order to fix it up.  However, I wouldn't want to start changing the naming scheme for other arches since we'd have to retest them.

On master, we are working towards a standard naming convention of `<image-name>:<tag>-<arch>` in order to make it easier in future to ship a manifest image as `<image-name>:<tag>`.

s390x is the most problematic architecture for us to support in-team because we can't use qemu to cross-build images from amd64, which we _can_ do for the other arches.

For this particular change, I think it's fine to parametrise the image org.  Only question in my mind is how we make sure this ends up in master too, otherwise we'll just regress it when we cut the next release branch.

**Comment by jose-bigio** [comment]
@fasaxc I think minimizing the changes that go into a release branch makes sense. The naming change going into Master seem good! 
 
As I mentioned before it is not too bad to work around this change.

**Pull request merged**
