### PR TITLE
Add batch labels to tests

### PR DESCRIPTION
**Pull request by lwr20**
## Description
Add batch labels to tests so that we can run the batches in parallel on Semaphore and speed up testing.

## Todos
- [x] Label Tests
- [x] Update Semaphore job config

### CODE REVIEW

**Comment by bcreane** [comment]
LGTM! Lance pointed me to the [modified semaphore build script](https://semaphoreci.com/calico/calico/settings) as well as [before](https://semaphoreci.com/calico/calico/branches/master/builds/689) and [after](https://semaphoreci.com/calico/calico/branches/pull-request-880/builds/7) job runs.

**Comment by lwr20** [comment]
@bcreane I assume you mean which batchnumber to assign their test to?  Yeah.  By default, if they don't add a batchnumber to their tests, they'll get assigned to batchnumber=0, so if they don't do anything, batch 0 will take longer.  I've deliberately made batch 0 shorter than the others, so that will be OK for a while.  But at some point we'll start needing to rebalance the tests between batches.  That will have to be done manually, and will involve another PR.  

I think we should just wait until the build time starts creeping up again and solve that problem when we get to it.

**Comment by caseydavenport** [comment]
> I think we should just wait until the build time starts creeping up again and solve that problem when we get to it.

Potentially wild suggestion.. should we maybe make a batch fail if it takes longer than some amount of time?  That way we'll be forced to rebalance batches or think hard about writing tests that execute quickly.

**Comment by lwr20** [comment]
@caseydavenport I think that's already the case with semaphore isn't it?  If your job takes too long, they just kill it.

**Comment by caseydavenport** [comment]
> What would you like it set to?

Not too bothered, maybe 20 minutes (since all our tests are below that now?)

Might be that that is too strict, in which case 25?

**Comment by lwr20** [comment]
Oh hang on - if I make that time shorter, all builds of revisions which don't include this merge will start failing.  So we can't be too strict for a little while (until all current open PRs merge this).  

Options are: 15, 30, 45, 60, 75, 90 mins.

**Comment by caseydavenport** [comment]
I think we'll have to make it 30 for now then, since some of these tests take longer than 15min (or could we shuffle things so that they complete in <15m?

**Comment by lwr20** [comment]
That *might* be possible...  But it'll require a whole lot more labelling than in this PR - this PR only labels whole test files.  To get below 18m we'd need to start separating tests from files into different batches.  

Feels like a second PR at that point?

**Comment by lwr20** [comment]
@robbrockbank said in slack about this PR: "anyhoo - i think merging as is, is fine".  If he hasn't merged it by tomorrow, I'll do it then :)

**Comment by robbrockbank** [comment]
I'm ok with this going in as is - it gets us some immediate improvements.

If we do lower the limit now that will only cause failures for existing PRs until they're rebased no?

**Comment by robbrockbank** [comment]
Only other comment I had (more of a question) is whether the semaphore "code" should be part of the Makefile target.

So `make semaphore_node <batch num>` could include the various git/grep checks....  not sure if that would be sensible or not.

**Comment by caseydavenport** [comment]
Yeah, I'm definitely in favor of merging this as-is without addressing any of the time limiting and maybe doing that in a future PR.  This is way better than it is today.

**Pull request merged**
