### PR TITLE
[DO NOT MERGE] Add missing RPM dependencies for Felix.

### PR DESCRIPTION
**Pull request by Symmetric**
Add the python-posix-spawn and python-etcd RPM dependencies to
the Felix RPM.

### CODE REVIEW

**Comment by Symmetric** [comment]
Can we get this PR through the build pipeline to test the artifacts? I haven't built the new Felix RPM manually yet.

**Comment by alexwlchan** [comment]
ok to test

**Comment by matthewdupre** [comment]
@fasaxc is doing some testing along with his new dependencies.

**Comment by fasaxc** [comment]
Closing in favour of #878

**Pull request closed without merging**
