### PR TITLE
Automated cherry pick of #4008: Update multiple dataplanes image

### PR DESCRIPTION
**Pull request by lxpollitt**
Cherry pick of #4008 on release-v3.16.

#4008: Update multiple dataplanes image

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 90fdc60ef4c053f6a582afb1d3cf131189a6d184

https://deploy-preview-4009--calico.netlify.app

**Review by neiljerram — APPROVED** [review]

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Pull request merged**
