### PR TITLE
Set etcd cluster token so that it is properly unique

### PR DESCRIPTION
**Pull request by neiljerram**
(`date +%s` gives us the number of seconds since 1970-01-01 00:00:00 UTC.)

### CODE REVIEW

**Comment by lwr20** [comment]
Also need to update `master/getting-started/kubernetes/installation/hosted/kubeadm/1.5/calico.yaml`

And similarly in `/v2.2`, `/v2.1`, etc

**Comment by matthewdupre** [comment]
Impact is that Felix won't notice if etcd is silently replaced, and could get confused.

**Comment by caseydavenport** [comment]
> And similarly in /v2.2, /v2.1, etc

I don't think we should do that for anything but the latest active release (v2.2) and `master/` unless there's a _really_ strong case for it.

@neiljerram could you give some more context as to why this is useful?  Does this have any potential to cause problems?  Does embedding the `date` commend in a Kubernetes manifest actually work?

**Comment by neiljerram** [comment]
@caseydavenport There's not really any context other than what is said here and in the linked issue.  As to whether the proposal actually works, I'm afraid I don't know yet; shortly after I posted this PR, we decided to work around the problem in calicoq by changing the default logging level from error to fatal, and since that I haven't been able yet to test the proposed change here.

**Comment by caseydavenport** [comment]
Going to close this for now since we've worked around it and an inline call to `date` doesn't actually work.

**Pull request closed without merging**
