### PR TITLE
tigera-operator: enable SELinux by default

### PR DESCRIPTION
**Pull request by cyclinder**
## Description

tigera-operator: enable SELinux by default

## Related issues/PRs

https://github.com/projectcalico/calico/issues/7851

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]
This LGTM, but I think we also need this change in the manifests within the projectalico/calico repository.

@mgleung WDYT? Is this OK?

**Comment by hjiawei** [comment]
Calico Enterprise has [`privileged: false`](https://downloads.tigera.io/ee/v3.17.1/manifests/tigera-operator.yaml) (and a few others) for Tigera Operator SecurityContext. We probably don't want this change in operator yaml for Calico Enterprise? That may raise questions from our customers. cc @rene-dekker

**Comment by hjiawei** [comment]
I think a better way to fix SELinux issue is to write custom SELinux policies. Making Tigera operator privileged on all platforms may result unwanted behaviors.

**Comment by caseydavenport** [comment]
Per the latest comments, going to close this one.

**Pull request closed without merging**
