### PR TITLE
[EU-675] Changed ebook banner and added link to top menu (release-v3.21)

### PR DESCRIPTION
**Pull request by Stanislav-Galchynski**

### CODE REVIEW

**Review by bcreane — APPROVED** [review]

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
