### PR TITLE
Add note about gateway router to FAQ

### PR DESCRIPTION
**Pull request by fasaxc**

### CODE REVIEW

**Comment by tomdee** [comment]
Is it worth adding a bit more detail to this, like the need for proxy_arp?
https://github.com/projectcalico/libnetwork-plugin/issues/66

**Comment by fasaxc** [comment]
@tomdee done.

**Comment by depay** [comment]
some words about host's route for `169.254.1.1` or `default` may be better

**Comment by fasaxc** [comment]
@depay Please feel free to submit a PR with your suggestion.

**Comment by CaoShuFeng** [comment]
LGTM, thanks.

**Comment by depay** [comment]
LoL, here coming as this PR merged :smile:

**Comment by fasaxc** [comment]
don't think this needs another round of review.

**Pull request merged**
