### PR TITLE
Update calico-containers links to calicoctl

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by gunjan5** [comment]
part of https://github.com/projectcalico/calicoctl/issues/1423

**Comment by gunjan5** [comment]
curious, why is this limited to `master` and `v2.0`?  shouldn't this be applied to `v1.5` and `v1.6`?

**Comment by caseydavenport** [comment]
Yes, it probably should be.

**Comment by gunjan5** [comment]
assigning it back to you in case if you want to squeeze in those changes for v1.5/v1.6

**Pull request merged**
