### PR TITLE
Check that BIRD is responsive as part of liveness

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Fixes https://github.com/projectcalico/calico/issues/7472

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Improve BIRD liveness probe so that it confirms BIRD is responsive over its socket
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by caseydavenport** [comment]
@matthewdupre the linked issue in the description provides an example reported by a user where BIRD had hung and was non-responsive, resulting in BGP sessions dropping. The user reported that manually restarting BIRD fixed the issue.

I agree that more triggers to restart BIRD can be concerning. That's generally why liveness probes are considered with a minimum-number of required failures before they come into effect.

On the other hand, why bother having liveness probes if they're just always going to default to "true" regardless of underlying system health?

**Comment by caseydavenport** [comment]
> actually makes things worse by restarting a lengthy process that would have eventually succeeded.

In this particular case, the pre-requisite is simply BIRD responding over its socket. I believe this should be a fairly safe check even in a loaded system, as BIRD should respond on its socket prior to any sort of data plane / synchronization logic that might be happening.

**Comment by phantomsixthplayer** [comment]
I believe I am facing this issue.

Kubernetes version:
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

Cloud provider:
```
bare-metal
```

Installation method: https://github.com/phantomsixthplayer/k8s-baseline-installation

Host OS: 
```
$ cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

$ uname -a
Linux k8s-control-plane-1 5.14.0-404.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jan 4 21:14:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Container runtime (CRI) and version:
```
$ containerd --version
containerd github.com/containerd/containerd v1.7.11 64b8a811b07ba6288238eefc14d898ee0b5b99ba
```

Related plugins (CNI) and versions: https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz


Description:
Following a clean installation using “kubeadm init,” the Calico nodes with pod names “calico-node-fjzj7” and “calico-node-v9d2h” in the “calico-system” namespace are encountering readiness probe failures. Despite my troubleshooting efforts, I haven’t been successful in resolving the issue. Any suggestions and ideas for troubleshooting welcome. See [logs](https://mega.nz/file/sgJhjbKC#Wnsmtragu6m5UYThQJ6R-FAOMBpgG8rtZYQg63cgDHg), and the installation steps above outline the process undertaken.

```
pod: calico-node-fjzj7 in namespace: calico-system
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Warning  Unhealthy  7m32s  kubelet            Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp [::1]:9099: connect: connection refused
  Warning  Unhealthy  7m31s  kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Warning  Unhealthy  7m30s  kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused


pod: calico-node-v9d2h in namespace: calico-system
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Warning  Unhealthy  10m   kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Warning  Unhealthy  10m   kubelet            Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp [::1]:9099: connect: connection refused


pod: calico-apiserver-54b4cd957d-cdbvv in namespace: calico-apiserver
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Warning  FailedMount  9m34s  kubelet            MountVolume.SetUp failed for volume "calico-apiserver-certs" : failed to sync secret cache: timed out waiting for the condition


pod: calico-apiserver-54b4cd957d-dc8bt in namespace: calico-apiserver
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Warning  FailedMount  9m35s  kubelet            MountVolume.SetUp failed for volume "calico-apiserver-certs" : failed to sync secret cache: timed out waiting for the condition


pod: calico-kube-controllers-6ddb6ddd65-qrrlg in namespace: calico-system
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Warning  FailedScheduling        10m                  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Warning  FailedCreatePodSandBox  10m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9c4119ee8f5f88b2020633e5f5177f5e18654b1011d979ba24bd8c7c56d7b723": plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/


pod: calico-typha-8684598794-g6sj2 in namespace: calico-system
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  11m   default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.


pod: csi-node-driver-8jkgq in namespace: calico-system
Events:
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Warning  NetworkNotReady         7m51s (x20 over 8m29s)  kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Warning  FailedCreatePodSandBox  7m49s                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2e2456fe7c48e00174f02ad2b17d1a25c556712a9f85c5f4642fdc70da8fcb45": plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/


pod: csi-node-driver-mmgz6 in namespace: calico-system
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Warning  NetworkNotReady         10m (x20 over 11m)   kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Warning  FailedCreatePodSandBox  10m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bbd297dedf3011c2dc00f572974dd8d5b435a676024c4e1e341739d535bfab75": plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/


pod: coredns-76f75df574-mxsn4 in namespace: kube-system
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Warning  FailedScheduling        13m                default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Warning  FailedCreatePodSandBox  10m                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b540694b788130a411f2359c77690ffb47a533a8d666673d0d6d7602fed7ce55": plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/


pod: coredns-76f75df574-sdsnz in namespace: kube-system
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Warning  FailedScheduling        13m                default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Warning  FailedCreatePodSandBox  10m                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "863e1a88b024e4dcf774900d7a57d3e2edf55f3483697fe4164ff4e070c9e90d": plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
```

After a reboot:
```
[administrator@k8s-control-plane-1 ~]$ kubectl describe pod calico-node-5rrf9 -n calico-system
Events:
  Type     Reason     Age   From     Message
  ----     ------     ----  ----     -------
  Warning  Unhealthy  42m   kubelet  Readiness probe failed: 2024-01-10 23:05:07.799 [INFO][3875] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  41m  kubelet  Readiness probe failed: 2024-01-10 23:05:37.773 [INFO][4392] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: felix is not ready: readiness probe reporting 503
  Warning  Unhealthy  41m  kubelet  Readiness probe failed: 2024-01-10 23:06:07.775 [INFO][4906] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  41m  kubelet  Readiness probe failed: 2024-01-10 23:06:07.831 [INFO][4918] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Normal   SandboxChanged  40m                kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          40m                kubelet  Container image "docker.io/calico/pod2daemon-flexvol:v3.27.0" already present on machine
  Normal   Created         40m                kubelet  Created container flexvol-driver
  Normal   Started         40m                kubelet  Started container flexvol-driver
  Normal   Pulled          40m                kubelet  Container image "docker.io/calico/cni:v3.27.0" already present on machine
  Normal   Created         40m                kubelet  Created container install-cni
  Normal   Started         40m                kubelet  Started container install-cni
  Normal   Pulled          40m                kubelet  Container image "docker.io/calico/node:v3.27.0" already present on machine
  Normal   Created         40m                kubelet  Created container calico-node
  Normal   Started         40m                kubelet  Started container calico-node
  Normal   SandboxChanged  37m                kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          37m                kubelet  Container image "docker.io/calico/pod2daemon-flexvol:v3.27.0" already present on machine
  Normal   Created         37m                kubelet  Created container flexvol-driver
  Normal   Started         37m                kubelet  Started container flexvol-driver
  Normal   Pulled          37m                kubelet  Container image "docker.io/calico/cni:v3.27.0" already present on machine
  Normal   Created         37m                kubelet  Created container install-cni
  Normal   Started         37m                kubelet  Started container install-cni
  Normal   Pulled          37m                kubelet  Container image "docker.io/calico/node:v3.27.0" already present on machine
  Normal   Created         37m                kubelet  Created container calico-node
  Normal   Started         37m                kubelet  Started container calico-node
  Warning  Unhealthy       37m (x2 over 37m)  kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
  Warning  Unhealthy       17m                kubelet  Readiness probe failed: 2024-01-10 23:30:04.826 [INFO][1512] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  16m  kubelet  Readiness probe failed: 2024-01-10 23:30:34.836 [INFO][1524] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  16m  kubelet  Readiness probe failed: 2024-01-10 23:31:04.847 [INFO][1850] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  16m  kubelet  Readiness probe failed: 2024-01-10 23:31:04.890 [INFO][1863] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  15m  kubelet  Readiness probe failed: 2024-01-10 23:31:34.827 [INFO][2304] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  15m  kubelet  Readiness probe failed: 2024-01-10 23:32:04.847 [INFO][2800] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
  Warning  Unhealthy  15m  kubelet  Readiness probe failed: 2024-01-10 23:32:13.365 [INFO][2998] confd/health.go 180: Number of node(s) with BGP peering established = 0
calico/node is not ready: BIRD is not ready: BGP not established with 10.0.1.1
[administrator@k8s-control-plane-1 ~]$ sudo netstat -anp |grep 179
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      6129/bird
tcp        0      0 10.0.1.1:179            10.0.2.1:41777          ESTABLISHED 6129/bird
unix  3      [ ]         STREAM     CONNECTED     24179    2030/pipewire-pulse
[administrator@k8s-control-plane-1 ~]$ sudo lsof -i :179
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
bird    6129 root    7u  IPv4  38392      0t0  TCP *:bgp (LISTEN)
bird    6129 root    8u  IPv4  38422      0t0  TCP k8s-control-plane-1:bgp->k8s-worker-node-1:41777 (ESTABLISHED)
[administrator@k8s-control-plane-1 ~]$ kubectl exec -it calico-node-5rrf9 -n calico-system -- /bin/bash -c "birdcl -s /var/run/calico/bird.ctl"
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), install-cni (init)
BIRD v0.3.3+birdv1.6.8 ready.
bird>
[root@k8s-control-plane-1 ~]# calicoctl node checksystem
Checking kernel version...
                5.14.0-404.el9.x86_64                                   OK
Checking kernel modules...
WARNING: Unable to detect the xt_u32 module as Loaded/Builtin module or lsmod
                xt_u32                                                  FAIL
WARNING: Unable to detect the xt_icmp module as Loaded/Builtin module or lsmod
                xt_icmp                                                 FAIL
                xt_multiport                                            OK
                ipt_ipvs                                                OK
                ipt_rpfilter                                            OK
WARNING: Unable to detect the ipt_set module as Loaded/Builtin module or lsmod
                ipt_set                                                 FAIL
                xt_addrtype                                             OK
                xt_set                                                  OK
                ip6_tables                                              OK
                ip_tables                                               OK
                xt_bpf                                                  OK
                xt_mark                                                 OK
                ipt_REJECT                                              OK
                xt_rpfilter                                             OK
                nf_conntrack_netlink                                    OK
                xt_conntrack                                            OK
WARNING: Unable to detect the xt_icmp6 module as Loaded/Builtin module or lsmod
                xt_icmp6                                                FAIL
                ip_set                                                  OK
                vfio-pci                                                OK
System doesn't meet one or more minimum systems requirements to run Calico
[root@k8s-control-plane-1 ~]# ls /lib/modules/$(uname -r)/kernel/net/netfilter/
ipset                          nf_conntrack_pptp.ko.xz   nf_nat_irc.ko.xz           nf_synproxy_core.ko.xz  nft_flow_offload.ko.xz  nft_quota.ko.xz          xt_AUDIT.ko.xz      xt_CONNSECMARK.ko.xz  xt_helper.ko.xz     xt_mark.ko.xz        xt_policy.ko.xz    xt_state.ko.xz
ipvs                           nf_conntrack_sane.ko.xz   nf_nat.ko.xz               nf_tables.ko.xz         nft_fwd_netdev.ko.xz    nft_redir.ko.xz          xt_bpf.ko.xz        xt_conntrack.ko.xz    xt_hl.ko.xz         xt_MASQUERADE.ko.xz  xt_quota.ko.xz     xt_statistic.ko.xz
nf_conncount.ko.xz             nf_conntrack_sip.ko.xz    nf_nat_sip.ko.xz           nft_chain_nat.ko.xz     nft_hash.ko.xz          nft_reject_inet.ko.xz    xt_cgroup.ko.xz     xt_cpu.ko.xz          xt_HL.ko.xz         xt_multiport.ko.xz   xt_rateest.ko.xz   xt_string.ko.xz
nf_conntrack_amanda.ko.xz      nf_conntrack_snmp.ko.xz   nf_nat_tftp.ko.xz          nft_compat.ko.xz        nft_limit.ko.xz         nft_reject.ko.xz         xt_CHECKSUM.ko.xz   xt_CT.ko.xz           xt_HMARK.ko.xz      xt_nat.ko.xz         xt_RATEEST.ko.xz   xt_tcpmss.ko.xz
nf_conntrack_broadcast.ko.xz   nf_conntrack_tftp.ko.xz   nfnetlink_cthelper.ko.xz   nft_connlimit.ko.xz     nft_log.ko.xz           nft_reject_netdev.ko.xz  xt_CLASSIFY.ko.xz   xt_dccp.ko.xz         xt_IDLETIMER.ko.xz  xt_NETMAP.ko.xz      xt_realm.ko.xz     xt_TCPMSS.ko.xz
nf_conntrack_ftp.ko.xz         nf_dup_netdev.ko.xz       nfnetlink_cttimeout.ko.xz  nft_counter.ko.xz       nft_masq.ko.xz          nft_socket.ko.xz         xt_cluster.ko.xz    xt_devgroup.ko.xz     xt_iprange.ko.xz    xt_NFLOG.ko.xz       xt_recent.ko.xz    xt_TCPOPTSTRIP.ko.xz
nf_conntrack_h323.ko.xz        nf_flow_table_inet.ko.xz  nfnetlink_hook.ko.xz       nft_ct.ko.xz            nft_nat.ko.xz           nft_synproxy.ko.xz       xt_comment.ko.xz    xt_dscp.ko.xz         xt_ipvs.ko.xz       xt_NFQUEUE.ko.xz     xt_REDIRECT.ko.xz  xt_TEE.ko.xz
nf_conntrack_irc.ko.xz         nf_flow_table.ko.xz       nfnetlink.ko.xz            nft_dup_netdev.ko.xz    nft_numgen.ko.xz        nft_tproxy.ko.xz         xt_connbytes.ko.xz  xt_DSCP.ko.xz         xt_length.ko.xz     xt_osf.ko.xz         xt_sctp.ko.xz      xt_TPROXY.ko.xz
nf_conntrack.ko.xz             nf_log_syslog.ko.xz       nfnetlink_log.ko.xz        nft_fib_inet.ko.xz      nft_objref.ko.xz        nft_tunnel.ko.xz         xt_connlabel.ko.xz  xt_ecn.ko.xz          xt_limit.ko.xz      xt_owner.ko.xz       xt_SECMARK.ko.xz   xt_TRACE.ko.xz
nf_conntrack_netbios_ns.ko.xz  nf_nat_amanda.ko.xz       nfnetlink_osf.ko.xz        nft_fib.ko.xz           nft_osf.ko.xz           nft_xfrm.ko.xz           xt_connlimit.ko.xz  xt_esp.ko.xz          xt_LOG.ko.xz        xt_physdev.ko.xz     xt_set.ko.xz
nf_conntrack_netlink.ko.xz     nf_nat_ftp.ko.xz          nfnetlink_queue.ko.xz      nft_fib_netdev.ko.xz    nft_queue.ko.xz         xt_addrtype.ko.xz        xt_connmark.ko.xz   xt_hashlimit.ko.xz    xt_mac.ko.xz        xt_pkttype.ko.xz     xt_socket.ko.xz
```

**Review by matthewdupre — APPROVED** [review]

**Comment by lwr20** [comment]
@phantomsixthplayer Its not clear to me from the diags provided that you've hit this problem.  The problem discussed in this PR is how to handle when BIRD is hung and unresponsive.  Whereas the diags you've provided show an expected readiness check failure when a BGP connection cannot be established (to 10.0.1.1)

**Pull request merged**
