### PR TITLE
Reflect different names in apply statement

### PR DESCRIPTION
**Pull request by wschoot**
Downloading calico-etcd.yaml gives a file named calico-etcd.yaml and not named calico.yaml. Also the CIDR warning should reflect this.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 4f551fd094c1b1d6d3444d625a6057fed089c5b1

https://deploy-preview-2782--calico.netlify.com

**Comment by caseydavenport** [comment]
@wschoot in order to make sure this applies to future releases, would you mind updating the PR to include the same changes to the corresponding file in _master?

**Comment by wschoot** [comment]
> @wschoot in order to make sure this applies to future releases, would you mind updating the PR to include the same changes to the corresponding file in _master?

I'd love to but as far as I can see, this is already pr'ed towards master, and I can't seem to find a _master branch. There's no mentioning of _master in the "contributing" docs. What exactly do you want me to do?

**Comment by caseydavenport** [comment]
Sorry, there was a stray underscore in that message... I just meant "master" (and, I was referring to the directory within this repo rather than a branch).

I was referring to this document: https://github.com/projectcalico/calico/blob/master/master/getting-started/kubernetes/installation/calico.md

The contributing docs don't cover this especially well, but I was referring to step #4 here: https://github.com/projectcalico/calico/blob/master/CONTRIBUTING_DOCS.md#overview

**Comment by caseydavenport** [comment]
Thanks!

**Comment by tmjd** [comment]
@wschoot what platform were you running your curl command on? The download command includes `-o calico.yaml` which is intended to cause the file to be named calico.yaml instead of the filename of the download link.

**Comment by wschoot** [comment]
@tmjd  I believe, but I'm not sure anymore as this has been a while ago, that the -o was not there or didn't reflect the desired hostname. I see the same thing happening again now on https://docs.projectcalico.org/v3.10/getting-started/kubernetes/installation/calico:
Step 1 on chapter "Installing with the Kubernetes API datastore—more than 50 nodes" downloads a file, names it using -o and step two uses the wrong filename (the original, instead of what -o specifies).

**Comment by tmjd** [comment]
Thanks for the quick response.
Yes it currently being broken is why I was looking at this PR. Someone noticed it was broken and tried to fix it with #3070 .
I think I realize what it was, your fix was against 3.8 and then you were requested to update the  master directory also but the same fixes weren't applicable. Looks like 3.8 used `-O` while master was using `-o calico.yaml`.
My bad, I was thinking `-o calico.yaml` hadn't worked for you but I think you were probably using `-O` when you came up with the proper fix for v3.8.
Thanks for your interest and contribution to Calico.

**Pull request merged**
