### PR TITLE
delete duplicate empty blanks

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

## Description

Delete all duplicate empty blanks in docs.

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit ff4a6a23e2807830f9e02f3b24a5fd2be9a4b1ba

https://deploy-preview-2466--calico.netlify.com

**Comment by neiljerram** [comment]
@daixiang0 Thank you for your interest and for submitting this PR!

However, I'm not sure we want a PR like this, because it will take a long time to review, without really adding useful value.  I understand that you probably generated the changes here in an automated way, and so it is very likely that they are all good and safe.  But we still need to review the changes in order to be sure about that, and that is time-consuming for 794 files!

If there are particular changes here that you think are more important, please could you submit those in separate PRs?

@caseydavenport WDYT?

**Comment by daixiang0** [comment]
@neiljerram i am very sensitive to the format of docs, so i write some tools to format which has tested many times. I know it may be only meaning to me, thanks.

**Comment by caseydavenport** [comment]
I'm inclined to agree, @neiljerram - while I too prefer to remove whitespace when I can, I think it's going to be counter-productive to attempt to do this across almost 800 files at once.

@daixiang0 I do appreciate the PR, and sympathize with your tendency to remove the whitespace! But, I think we can't accept this at the moment in its current form.

**Pull request closed without merging**
