### PR TITLE
Added Openshift link

### PR DESCRIPTION
**Pull request by ToroNZ**
## Description

Added missing Openshift link

## Todos

- [X] Tests
- [x] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by emanic** [comment]
@ToroNZ Thank you! Sorry for the hassle with the squashing of the commits, looks like you've just opened a new PR, that works too. don't worry about the `htmlproofer` error here, that's on our end and I can override it, but we do need you to sign the CLA. Looks like you managed to sign it before but perhaps you used a different method for this PR? These instructions could be helpful https://help.github.com/articles/setting-your-commit-email-address-in-git/. Thanks!

**Comment by ToroNZ** [comment]
No hassle, I'm just hopeless when it comes to Git.
This time I used my laptop and Git grabbed my local user (tomas), trying to find out now if I can change the author on this commit.

**Comment by emanic** [comment]
Hi @ToroNZ no worries, it happened to me as well one time. I think after you set your user name and email correctly as in previous link, you then would need to force push. The force push is OK because it is to your own fork. 😄  

If I were you, _assuming your fork is set as `origin` remote and Calico is set as `upstream` remote (you can check with `git remote -v`)_, I would do this:
1. Set your git email and user name in your command-line client. (link provided previously)
2. Do `git reset --hard 4f0fabd3a75b8f52995359fa5011d76c2e4cfd37` (brings you back to your single original commit)
3. Then I would do `git rebase upstream/master`.
4. This should replay your single commit on top of the latest master.
5. After that, you should be able to do `git push origin +master` (a force push to your own fork, which I am assuming is `origin`)
6. this should result in a single commit and also I think GitHub will then be able to recognize you so you can sign the CLA.

If that's too much bother, perhaps you can just close this and open a new PR? 😄

**Comment by ToroNZ** [comment]
@emanic Well, I learned something new today! Cheers for that, I think it worked.

**Comment by emanic** [comment]
@ToroNZ great! LGTM thanks so much. 👍

**Pull request merged**
