### PR TITLE
Corrects the Felix usage reporting options

### PR DESCRIPTION
**Pull request by emanic**
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 2e8914383e2fb5a8a13ab2a5cc3a99d82331af01

https://deploy-preview-2348--calico.netlify.com

**Comment by fasaxc** [comment]
I don't think this is correct. Felix has several configuration sources, this page documents the format that you need to us in the felix configuration file/env var, which (very sadly!) is different to the format used in the YAML FelixConfig resource.

**Comment by emanic** [comment]
OK I thought you said that all environment variables are passed as strings. Can you tell me then what is the correct datatype here? @fasaxc

**Comment by fasaxc** [comment]
I think the doc is already correct.  Yes, all env vars are strings, but the syntax is is telling you how to format that string so that Felix can parse it.  YAML is a typed format so things are a little different there.

**Pull request closed without merging**
