### PR TITLE
Correct description of Felix config parameters.

### LINKED ISSUE #859: Remove StartupCleanupDelay, it's not longer used
Docs still contain references to StartupCleanupDelay (and possibly other old Felix config params), which are no longer used.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

- Remove StartupCleanupDelay, which hasn't been present since 2.0.
- Fix Iptables*AllowAction, which was split into two fields.

Fixes #859

## Todos

- [x] Tests
- [x]  Documentation
- [x] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by emanic** [comment]
@fasaxc Sorry this seems to have slipped through the cracks. Is this PR still valid? Thanks!

**Comment by fasaxc** [comment]
@emanic Yes, it's still correct.

**Comment by fasaxc** [comment]
Needs to be merged to v2.6 directory...

**Comment by neiljerram** [comment]
Continued in #1221

**Pull request closed without merging**
