### PR TITLE
Update table styles and table rows

### PR DESCRIPTION
**Pull request by Stanislav-Galchynski**
## Description

This PR provides style updates for the compare table.

### CODE REVIEW

**Review by alexvarsh — APPROVED** [review]
Confirmed with Barbara

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by bcreane — APPROVED** [review]

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
