### PR TITLE
Adding Canal to master and v3.0 docs

### PR DESCRIPTION
**Pull request by tmjd**
## Description

Adding docs only to master though this installation is broken due to a problem that will be addressed soon. The problem is expected to be fixed in a 3.0.x point release and so should be safe to add to the master docs.
The doc is a copy of what was added to the v2.6 docs but the manifests have been updated for v3.x.

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by ozdanborne** [comment]
@tmjd what's up with this guy?

**Comment by tmjd** [comment]
It is waiting on me finishing up the testing that I hope to finish today.
The docs are a copy of what is in v2.6, If you want to take a look at the manifest please do.
I'm going to go ahead and copy the master changes to v3.0 so this PR is ready when I'm happy with the changes.

**Comment by tmjd** [comment]
@emanic Could you take a look at this? There are no doc changes compared to the v2.6 docs but can you let me know if I got the canonical_url and redirect_from right?
@caseydavenport do you want to take a look at the manifest?

**Comment by emanic** [comment]
OK great, looks like the ST is passing now and the htmlproofer error is expected because of chicken egg problem (new page). We can use admin override for these.

**Pull request merged**
