### PR TITLE
Test the master release stream by default.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description
Test the master release stream by default.  This is certainly what I'd expect `make st` to do by default but I'm not sure why it was pinned to v2.3 before so any insight there would be good!

## Todos
- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
We'll need to sort out how this impacts the release process in RELEASING.md before we can merge this, I think.

That's on my plate, but probably won't happen this week.

**Comment by caseydavenport** [comment]
> why it was pinned to v2.3 before so any insight there would be good!

Yeah.. it's a bit weird. It was pinned to v2.3 because our release process has us update that to the desired release stream and merge to master before cutting the release from master.

So, if we want to keep this, we'll at least need to add "after the release, revert release stream to master" to RELEASING.md, but that's really icky so I think we'll want to do something else.

**Comment by caseydavenport** [comment]
It's a major PITA for the release process if we merge this as is.

For each release, we'd need to:
- Change release stream from master -> next release
- Commit changes, run through CI, merge, cut release
- Submit another PR to change from release back to master

**Comment by ozdanborne** [comment]
Closing as this PR is a few months old, and it seems there is a larger discussion that needs to happen before we make this change.

**Pull request closed without merging**
