### PR TITLE
[release-v3.27] Manual pick #8827: Improve cni-plugin binary install verification

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of https://github.com/projectcalico/calico/pull/8827 on release-v3.27.

https://github.com/projectcalico/calico/pull/8827: Improve cni-plugin binary install verification

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Improve cni-plugin binary install verification.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]

**Comment by ialidzhikov** [comment]
Same failures as the ones described in https://github.com/projectcalico/calico/pull/8842#issuecomment-2121878442.

**Comment by ialidzhikov** [comment]
> LGTM - we'll probably want this picked to v3.28 as well (don't think it made that one)

Thank you! I somehow missed that the corresponding PR that introduced the issues was merged in v3.28. I now created https://github.com/projectcalico/calico/pull/8844.

**Pull request merged**
