### PR TITLE
Adjust confd log level

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Allow configuration of confd's log level on startup.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by robbrockbank** [comment]
Looks fine, but probably not the approach I would have taken.

The client code already listens to the BGPConfiguration, so I would have watched for updates to the LogSeverityScreen field for the node and globally and adjusted the log level real time based on that config.

**Comment by caseydavenport** [comment]
@robbrockbank yes that sounds fine and I considered it. I don't think they're mutually exclusive changes.

I'm happy to do that if I have time, but this is much quicker.

**Comment by caseydavenport** [comment]
Perhaps it should share an environment variable with BIRD at least though, to match the datastore config model.

**Comment by robbrockbank** [comment]
If we do you environs - is the expected case that ENVs would trump etcd config if specified?

**Comment by caseydavenport** [comment]
@robbrockbank yes, I think so.

Perhaps it should really be done in confd, and then this PR simply becomes removing the `log-level` option when starting confd.

**Comment by caseydavenport** [comment]
@robbrockbank I've updated to not set the log level at all.

Once https://github.com/projectcalico/confd/pull/57 is merged we'll get the configuration bit back.

**Comment by robbrockbank** [comment]
LGTM - ended up being a slightly different PR than originally intended :-)

**Comment by robbrockbank** [comment]
sorry pressed the wrong button

**Comment by caseydavenport** [comment]
Docs failure is an htmlproofer flake

**Pull request merged**
