### PR TITLE
Clarifies the use of master in canonical URLs

### PR DESCRIPTION
**Pull request by emanic**
## Description

- Clarifies what to use for a canonical URL when the page exists only in master.
- Updates RELEASING.md to handle for this case.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit f30f78389beecc55bf86a6a910d8b607204190f5

https://deploy-preview-2386--calico.netlify.com

**Comment by neiljerram** [comment]
I wonder if more of this could be automated.  Is the algorithm as follows?

```
For each *.md page:
  Find the set of numeric (i.e. excluding 'master') versions that have a page with the same path (after the version)
  If that set is non-empty:
    Set the canonical_url for the page to the path with the most recent version.
    // Note, this includes adding a canonical_url if not already present, or updating if not already correct.
```

If that is the correct algorithm, we could entirely automate it at release time, and then we wouldn't need guidance on what to do with a master-only page.

This would also fix up pages (which I keep coming across) where the canonical_url has somehow become out of date.

**Comment by fasaxc** [comment]
If it can be automated, we can probably remove it from the checked-in files completely and generate it as part of the build. It's the main source of conflicts when merging to closed source.

**Comment by fasaxc** [comment]
Ditto for the title, we should be able to use a pre-processing step in the build to apply templating to the title as we do for the content.

**Comment by emanic** [comment]
Thanks you guys. I think that the logic @neiljerram outlines could work in some cases but the problem is, we need to anticipate that pages may shift locations. So that is what would make the automation difficult. 

As far as the titles, I'm not quite sure exactly what preprocessing you would propose @fasaxc , could you elaborate? I know that the inability to use variables in the titles is a sticking point and have been trying to figure out a way to do that.

**Pull request closed without merging**
