### PR TITLE
Remove unnecessary branching

### PR DESCRIPTION
**Pull request by nuczzz**
## Description
Simplify code logical.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@nuczzz you'll need to sign the CLA in order to make the bot happy before we can merge. Thanks for the PR!

**Comment by nuczzz** [comment]
> 
ok, I'll do it right away


>

**Comment by nuczzz** [comment]
> 

@caseydavenport  Yes, thank you for your reminder. I've finished it

**Pull request merged**
