### PR TITLE
Docs-update-arch-diagram

### PR DESCRIPTION
**Pull request by bmckercher123**
## Update architecture diagram

- Both EE and OS architecture diagrams are updated by UX team
- Requires final review from Casey
- Merge to nightly and cherrypick to latest

### CODE REVIEW

**Comment by caseydavenport** [comment]
@bmckercher123 just saw this one. Looks like the new image includes enterprise components - is that intentional? Seems wrong at a glance.

**Comment by bmckercher123** [comment]
This diagram was done by Alex V.'s team in a tool called Figma. Looks like several misses that need correction.

**Comment by bmckercher123** [comment]
@casey. Take a look at this update with corrections: https://www.figma.com/file/TVdX2BHhNOIZCKSSkz5t6a/Calico-Cloud-(Copy)?node-id=184%3A0

**Review by caseydavenport — APPROVED** [review]

**Comment by bmckercher123** [comment]
@caseydavenport 
The image was created in a UX tool called Figma. So the link you reviewed above, was only the browser view of the file; I have not added to the PR yet. I wanted to make sure it was correct before I saved to .png. So we can either revert, or I can just open up a new PR. Does a revert cause any side effects?

**Pull request merged**
