### PR TITLE
Felix FVs: fix SCTP tests.

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

Split pre-conncheck cleanup into a separate phase. Test was running one checker's cleanup in prallel with another's check.  If they used the same source/dest that could conflict by killing the check's conntrack entry.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Comment by fasaxc** [comment]
The failures in CI are _other_ known flakes and the Windows runs are timing out due to another problem so I killed the CI.

**Review by tomastigera — COMMENTED** [review]
I definitely removes the between cleaners and the check itself :+1: I only wonder if there may be clashes between the cleaners themselves. If not now, then perhaps later. Maybe we should run simultaneously only those that run on different nodes?

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by fasaxc** [comment]
Don't think I've seen the actual commands fail but let's be defensive.  Also, made it only run the cleanup between retries.

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.

**Review by tomastigera — APPROVED** [review]
LGTM

**Pull request merged**
