### PR TITLE
Add initContainer ports to WorkloadEndpoint

### PR DESCRIPTION
**Pull request by george-angel**
## Description

Type: bug fix

This allows access using named ports in NetworkPolicy when they are exposed in the Pod inside initContainer attribute.

This is relevant now as initContainer is the recommended way of running sidecars which a long lived and will more commonly expose ports.

## Related issues/PRs

Fixes: https://github.com/projectcalico/calico/issues/8881

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Support for using named ports in NetworkPolicy when exposed via an initContainer.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by matthewdupre — APPROVED** [review]

**Review by caseydavenport — APPROVED** [review]

**Comment by caseydavenport** [comment]
@george-angel apologies... I am not sure how this didn't get merged but it has a conflict now so could use a rebase.

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by caseydavenport** [comment]
Tried using GH UI to resolve the conflict, we'll see how that goes :grin:

**Comment by george-angel** [comment]
> Tried using GH UI to resolve the conflict, we'll see how that goes 😁

Sorry - was on leave, back today, thank you for the rebase and picking it up again :bow:

**Pull request merged**
