### PR TITLE
Tooooo many m's in recommend

### PR DESCRIPTION
**Pull request by gunjan5**
You guys are having waaay too much fun with this! STSPMQD 🌮

## Todos

- [x] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 2b5e36733682794280b803ce97e9c18e9b1dcafe

https://deploy-preview-2534--calico.netlify.com

**Comment by briansan** [comment]
what are these acronyms...

**Comment by briansan** [comment]
I just realized that was my documentation :sadpanda:

**Comment by briansan** [comment]
does this mean that you're making use of this feature now? :D

**Comment by caseydavenport** [comment]
I think it means @gunjan5 saw I closed his issue: https://github.com/projectcalico/calico/issues/547

**Comment by gunjan5** [comment]
Yes yes yes, saw the notification from my old issue #547 and my super sharp grammar sense kicked in and caught the wild typo! I bet @caseydavenport didn't review the original doc 🦅

**Comment by gunjan5** [comment]
oh and @briansan `JGOC` means "Jolly Good something-something" I think it's British for LGTM? and ask Turk about `STSPMQD`

**Comment by lwr20** [comment]
Presumably Jolly Good Old Chap?

**Pull request merged**
