### PR TITLE
Updating flannel version to v0.16.3

### PR DESCRIPTION
**Pull request by cyclinder**
## Description

Updating flannel version to v0.16.3

## Related issues/PRs

https://github.com/projectcalico/calico/issues/5563

## Todos

- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
Update flannel to version v0.16.3
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Thanks for the PR!

**Comment by cyclinder** [comment]
hi @caseydavenport, When will this PR be merged into master and where is the problem that it has not been merged so far?

**Comment by caseydavenport** [comment]
@cyclinder sorry, I thought I had marked this one for auto-merge but it appears not.

**Comment by cyclinder** [comment]
@caseydavenport  Thanks!

**Pull request merged**
