### PR TITLE
Add logs for felix status reporting events.

### PR DESCRIPTION
**Pull request by fasaxc**

### CODE REVIEW

**Comment by fasaxc** [comment]
@matthewdupre this would be useful for diagnosing @DaveLangridge's scale-testing issue

**Comment by DaveLangridge** [comment]
Does this log when the status of a felix instance changes? (Doesn't look like it.) That would be useful. Should be an unusual event.

**Comment by matthewdupre** [comment]
Marking this do not merge until I can check up on the interaction with the mech driver move.

**Comment by fasaxc** [comment]
@DaveLangridge we already log if the key times out.  This adds a log when a felix checks in too as well as top and tail logs for processing a resync.

**Comment by fasaxc** [comment]
Closed in favour of https://review.openstack.org/249904

**Pull request closed without merging**
