### PR TITLE
Move the imageNames list from _config.yml to _data/imageNames.yml

### PR DESCRIPTION
**Pull request by Jingzhao123**
For supporting the different image name for various versions, the
image name list was removed from global configuration _config.yml.
And add a configuration file imageNames.yml in _data folder for
supporting different versions.
By this way, we can unbind the imageName with versions. It can
support the different images in various versions.

Signed-off-by: Jingzhao <Jingzhao.Ni@arm.com>

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 9482b3fbec7e99d5bf2c208720d6c33c30b05674

https://deploy-preview-2306--calico.netlify.com

**Comment by neiljerram** [comment]
@Jingzhao123 I presume there's a specific reason for doing this.  Could you comment here what that is?

**Comment by Jingzhao123** [comment]
> @Jingzhao123 I presume there's a specific reason for doing this. Could you comment here what that is?

Sure. removing the imageName list from _config.yml to _data/imageNames.yml and adding specific version supporting can help modifying the image path based on different versions. 
E.g:
If we want to change the image path of calico/node only on v3.3 but without affecting any others, it can not be completed based on the latest infrastructure. Since it do not separate different version. 
Now, by adding some version support in _data/imageNames.yml, it could be well supported.

**Comment by neiljerram** [comment]
@Jingzhao123 That is a general reason for this kind of change, but not a specific need. Without a specific need, it is better for us not to make this change, because it would increase our ongoing maintenance costs.

**Comment by Jingzhao123** [comment]
> @Jingzhao123 That is a general reason for this kind of change, but not a specific need. Without a specific need, it is better for us not to make this change, because it would increase our ongoing maintenance costs.

Sorry for my unclear express. As we knows, the multi-arch has been supported from Calico v3.2. For deploying on different platform, the yaml configuration files should support multi-arch image path. But now, the "quay.io/calico/xxx" path does not support multi-arch. So i want to modify them from "quay.io/calico/xxx" to "calilco/xxx" which can support multi-arch version only on specific versions. 

Actually, i am deploying Calico on arm64 platform. I found that the configuration files in instruction does not supported well enough for multi-arch. So I want to do some work for it.

**Comment by Jingzhao123** [comment]
> > @Jingzhao123 That is a general reason for this kind of change, but not a specific need. Without a specific need, it is better for us not to make this change, because it would increase our ongoing maintenance costs.
> 
> Sorry for my unclear express. As we knows, the multi-arch has been supported from Calico v3.2. For deploying on different platform, the yaml configuration files should support multi-arch image path. But now, the "quay.io/calico/xxx" path does not support multi-arch. So i want to modify them from "quay.io/calico/xxx" to "calilco/xxx" which can support multi-arch version only on specific versions.
> 
> Actually, i am deploying Calico on arm64 platform. I found that the configuration files in instruction does not supported well enough for multi-arch. So I want to do some work for it.

@neiljerram Do you have any suggestions about it ?

**Comment by fasaxc** [comment]
@Jingzhao123 We publish multi-arch images to dockerhub.  I think what needs to happen is for us to change the images from `quay.io/calico/node` to just `calico/node` (with no arch-specific suffix); then the manifests should work on any arch.  Can you try making that change in your manifests and see if it works for you?

**Comment by Jingzhao123** [comment]
> @Jingzhao123 We publish multi-arch images to dockerhub. I think what needs to happen is for us to change the images from `quay.io/calico/node` to just `calico/node` (with no arch-specific suffix); then the manifests should work on any arch. Can you try making that change in your manifests and see if it works for you?

Of course OK. I have ever pushed one patch about it before, but it was not accepted by community since the community want to modify the files infrastructure for supporting different image path on different versions. So I have to do some modification about infrastructure. 
Now, Could i directly modify it from 'quay.io/calico/xxx' to 'calico/xxx' in _config.yml? @neiljerram @fasaxc

**Comment by fasaxc** [comment]
@Jingzhao123 who pushed back on that approach?

**Comment by Jingzhao123** [comment]
> @Jingzhao123 who pushed back on that approach?

casedavenport
@caseydavenport

**Comment by Jingzhao123** [comment]
I write a shell for checking the difference of image versions between dockerhub and quay.io repo. After checking it, i found that the image from dockerhub is same with the one from quay.io. The script is attached as followings.
You can extract the package and run the shell totalTest.sh for checking the versions. (The docker software required)
 
[checkImages.zip](https://github.com/projectcalico/calico/files/2640326/checkImages.zip)

**Comment by caseydavenport** [comment]
@Jingzhao123 thanks for your effort on this.

I've merged https://github.com/projectcalico/calico/pull/2364 which accomplishes the goal of this PR, so I'm going to close this one.

**Pull request closed without merging**
