### PR TITLE
proxy_delay setting failure should not be a critical error

### PR DESCRIPTION
**Pull request by cyclinder**
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

## Related issues/PRs

https://github.com/projectcalico/calico/issues/5341

## Todos

- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
proxy_delay setting failure should not be a critical error
```

### CODE REVIEW

**Comment by fasaxc** [comment]
@mgleung are we already setting this in the CNI plugin?  If not we should be in case felix can't set it.

**Comment by caseydavenport** [comment]
/sem-approve

@mgleung still an open question for you :)

**Comment by cyclinder** [comment]
@mgleung  Can you take a look ?

**Comment by mgleung** [comment]
Ah sorry, I missed the notification. My bad everyone.

@fasaxc we attempt to set this in both the cni plugin and felix (in privileged mode) though I guess with these changes, it's not guaranteed that the setting will be set in either. I know you raised some concerns about the extra latency this might cause so not sure if you have any other thoughts around ways to giving a best effort try to setting the values.

**Review by mgleung — APPROVED** [review]
@cyclinder changes look good to me. Thanks for the PR and sorry for the wait.

**Comment by cyclinder** [comment]
@mgleung Thanks！

**Comment by caseydavenport** [comment]
@cyclinder I think this PR needs a rebase in order to pick up some build fixes that went into master, that should get the tests passing so we can merge.

**Comment by cyclinder** [comment]
@caseydavenport  Thanks for your notice, I've rebase the latest master

**Comment by cyclinder** [comment]
@caseydavenport hi，this pr is still need rebase? I saw still not merge until now，Is there something wrong？

**Comment by caseydavenport** [comment]
@cyclinder nope, looks good now. Sorry I missed it. Running the tests now.

**Comment by cyclinder** [comment]
@caseydavenport Thanks!

**Pull request merged**
