### PR TITLE
Fix the node-driver-registrar binary format for archs

### PR DESCRIPTION
**Pull request by mkumatag**
## Description

BUILD_PLATFORM is passed with valid values to build the appropriate binaries on the target platform.

Reference from [kubernetes-csi/node-driver-registrar](https://github.com/kubernetes-csi/node-driver-registrar/blob/5059b9626f8233656182adf2db79c473c7089367/release-tools/build.make#L73) repository
```make
# BUILD_PLATFORMS contains a set of tuples [os arch buildx_platform suffix base_image addon_image]
```

so we need to worry about first 3 entries of the tuple: os, arch and build_platform, hence modified the code to use these values appropriately.

>Note: suffice is not required because we are renaming the binary in the [makefile](https://github.com/projectcalico/calico/blob/6db15690a40618bdae9504eb8d3f4c48f9e12ac1/pod2daemon/Makefile#L107) already.

## Related issues/PRs
fixes: #7351

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by caseydavenport** [comment]
pinging @mgleung for this one

**Comment by mkumatag** [comment]
> pinging @mgleung for this one

ping @mgleung

**Review by caseydavenport — APPROVED** [review]

**Comment by caseydavenport** [comment]
OK I'll do it myself :rofl:

**Pull request merged**
