### PR TITLE
Fixing small typo (should say BGPConfiguration)

### PR DESCRIPTION
**Pull request by stevegaossou**
## Description
Small documentation fix for `BGPConfiguration` doc.

## Todos
- [ ] ~~Tests~~
- [x] Documentation
- [ ] ~~Release note~~

## Release Note
```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 4efd73cb054260b8d65f6486f9fdbe9c34d11cd3

https://deploy-preview-2469--calico.netlify.com

**Comment by caseydavenport** [comment]
@stevegaossou this LGTM. A couple of things:

- We should make this change to the equivalent file in the `master/` directory so that it applies to future releases as well.
- The CLA bot wants you to sign the CLA :)

**Comment by stevegaossou** [comment]
> - We should make this change to the equivalent file in the master/ directory so that it applies to future releases as well.

Done. 

> - The CLA bot wants you to sign the CLA :) 

Aaand done.

**Comment by caseydavenport** [comment]
@stevegaossou Actually, since this PR went up we've added a v3.6 directory as well... could you add this change there?


Thanks!

**Comment by stevegaossou** [comment]
> @stevegaossou Actually, since this PR went up we've added a v3.6 directory as well... could you add this change there?

Done.

**Pull request merged**
