### PR TITLE
Update armv7 base images for alpine:3.18

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

/kind cleanup

/docs-not-required

/release-note-not-required

### CODE REVIEW

**Comment by mgleung** [comment]
@yanggangtony is there something we should be aware of in the newest alpine image? I know we also pull some libs from older alpine images for calicoctl, node, and apiserver. Do we need to update those as well?

**Comment by yanggangtony** [comment]
@mgleung 

Yes , that sounds good to me..
But i search of keyword 'alpine:' , found these base image have a lot of different versions..
like the pic below.
image

Should we unify all of these to the latest?
In my opinion , alpine's latest version maybe the good choice for develop or product environments.
what do you think about that?

**Comment by caseydavenport** [comment]
> Should we unify all of these to the latest?

It would be nice to use a consistent alpine version, yeah

**Comment by yanggangtony** [comment]
Update to latest version : 3.17.2

**Comment by caseydavenport** [comment]
Build is failing:

```
 > [2/5] RUN apk add --no-cache     python     netcat-openbsd:
#0 0.120 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
#0 0.254 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
#0 0.501 ERROR: unable to select packages:
#0 0.531   python (no such package):
#0 0.531     required by: world[python]
------
```

**Comment by yanggangtony** [comment]
the pr 's time is a lot months ago.
Now the alpine is 3.17.3 and 3.18.
[alpine releases](https://www.alpinelinux.org/releases/)
😂😂

**Comment by caseydavenport** [comment]
Yeah, sorry about the long cycle time on this one.

**Comment by yanggangtony** [comment]
@caseydavenport 
Yep . I will go the 3.18.

**Review by caseydavenport — APPROVED** [review]

**Comment by yanggangtony** [comment]
@caseydavenport 
Thanks for trigger the ci.
But i see the ci is error .
I can not access it . 
Is there a method to get the detail of the ci 's result?
image
image

**Comment by caseydavenport** [comment]
@yanggangtony I've uploaded the test output here: https://gist.github.com/caseydavenport/65c6adddc3c7be7cdd743b84932748ba

It's not immediately obvious how it's related to your changes, but it does seem to be happening consistently.

**Comment by yanggangtony** [comment]
@caseydavenport 
Thanks for the log share.
Can not figure out the immediate error hints.
 This time , the error
```
 > [2/5] RUN apk add --no-cache     python     netcat-openbsd:
#0 0.120 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
#0 0.254 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
#0 0.501 ERROR: unable to select packages:
#0 0.531   python (no such package):
#0 0.531     required by: world[python]
------
```
have no appear , because i update the apk add , the alpine 3.17 or 3.18 is adapted to the py3.

**Pull request closed without merging**
