### PR TITLE
[release-v3.26] Manual pick #8827: Improve cni-plugin binary install verification

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of https://github.com/projectcalico/calico/pull/8827 on release-v3.26.

https://github.com/projectcalico/calico/pull/8827: Improve cni-plugin binary install verification

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Improve cni-plugin binary install verification.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]
/sem-approve

**Comment by ialidzhikov** [comment]
There is 1 failure in the cni-plugin tests:
```
  Unexpected error:15:17
      <*errors.Err | 0xc0030f3ea0>: {15:17
          message: "",15:17
          cause: <*types.Error | 0xc0032bf9e0>{15:17
              Code: 999,15:17
              Msg: "pods \"test-pod-37\" not found",15:17
              Details: "",15:17
          },15:17
          previous: <*types.Error | 0xc0032bf9e0>{15:17
              Code: 999,15:17
              Msg: "pods \"test-pod-37\" not found",15:17
              Details: "",15:17
          },15:17
          file: "github.com/projectcalico/calico/cni-plugin/internal/pkg/testutils/utils_linux.go",15:17
          line: 254,15:17
      }15:17
      pods "test-pod-37" not found15:17
  occurred15:17
  /go/src/github.com/projectcalico/calico/cni-plugin/tests/calico_cni_k8s_test.go:3109
```

This looks more like a flake. 

There is also 1 error in the After pipeline runs (`Reports`):
```
* Pulling artifacts:00:00
$ /usr/local/bin/artifact pull workflow test-results/f2da8624-562c-4dd9-b07e-80cb648c71a0 -d /tmp/test-results296593373500:00
* Pulling artifacts failed: exit status 100:00
[May 20 18:42:01.881] Error pulling artifact: failed to generate signed URLs - hub returned 404 status code00:00
[May 20 18:42:01.881] Please check if the artifact you are trying to pull exists.00:00
Error: exit status 100:00
Usage:00:00
  test-results gen-pipeline-report [<path>...] [flags]00:00
Flags:00:00
  -f, --force   force artifact push, passes -f flag to artifact CLI00:00
  -h, --help    help for gen-pipeline-report00:00
Global Flags:00:00
      --config string         config file (default is $HOME/.test-results.yaml)00:00
  -N, --name string           name of the suite00:00
      --no-compress           skip gzip compression for the output00:00
  -p, --parser string         override parser to be used (default "auto")00:00
  -S, --suite-prefix string   prefix for each suite00:00
      --trace                 trace output00:00
  -v, --verbose               verbose output00:00
Error: exit status 1
```

None of these failures seem to tbe related to this PR. Can we retrigger the checks?

**Comment by caseydavenport** [comment]
I believe that was a flake recently fixed in this PR: https://github.com/projectcalico/calico/pull/8798

I'll get that one cherry-picked back, but shouldn't impact this pick.

**Pull request merged**
