### PR TITLE
DOCS-1002: Backport source fixes docusaurus

### PR DESCRIPTION
**Pull request by ctauchen**
Fixes https://tigera.atlassian.net/browse/DOCS-1002

Backporting source-fix changes for the docs migration.

### CODE REVIEW

**Comment by ctauchen** [comment]
@bmckercher123 Can you take a look?

**Review by bmckercher123 — APPROVED** [review]
LGTM

**Comment by ctauchen** [comment]
@caseydavenport This keeps failing tests in Semaphore, but it's all docs or README-related fixes. Can you override and merge? Or is there something else we can do here?

**Comment by ctauchen** [comment]
> @caseydavenport This keeps failing tests in Semaphore, but it's all docs or README-related fixes. Can you override and merge? Or is there something else we can do here?

Build magically fixed itself!

**Pull request merged**
