### PR TITLE
Remove some unused imports

### PR DESCRIPTION
**Pull request by alexwlchan**
I ran `flake8 *.py **/*.py` over the entire repo, and corrected all
the reports of unused imports.

### CODE REVIEW

**Comment by alexwlchan** [comment]
ok to test

**Comment by fasaxc** [comment]
LGTM.  Happy for you to merge once the PR builds have passed.

**Comment by fasaxc** [comment]
retest this please

**Comment by alexwlchan** [comment]
PR builds have passed; merging

**Pull request merged**
