### PR TITLE
[release-v3.23] cherry-pick #6287: Support ppc64le image

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

## Description

Add support for ppc64le apiserver build image.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Build ppc64le image for calico/apiserver.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by yussufsh** [comment]
cc @caseydavenport

**Review by caseydavenport — APPROVED** [review]

**Comment by mkumatag** [comment]
lemme check my luck!

/sem-approve

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by yussufsh** [comment]
closing as ppc64le manifest is available in `quay.io/calico/apiserver:v3.24.0`

**Pull request closed without merging**
