### PR TITLE
Automated cherry pick of #4010: Add about Kubernetes egress

### PR DESCRIPTION
**Pull request by lxpollitt**
Cherry pick of #4010 on release-v3.16.

#4010: Add about Kubernetes egress

### CODE REVIEW

**Comment by bcreane** [comment]
too bad the squash isn't working.

**Review by bcreane — APPROVED** [review]

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, squash the commits when I merge it, and leave the branch after I've merged it.

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit ea41cca4113d3fa0de977ec578c679aab89bccb1

https://deploy-preview-4018--calico.netlify.app

**Pull request merged**
