### PR TITLE
Fix bug in handling of RV too old errors

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

This PR attempts to capture errors of the form "ResourceVersion for the provided list is
too old" and retry the list with a zero'd out revision number.

It also clears the resync flag after a successful sync so that we'll
only retry a List() if an error is hit.

## Related issues/PRs

Fixes https://github.com/projectcalico/calico/issues/6032

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Fix bug where Calico would not recover after listing from a too old resource version
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by fasaxc** [comment]
I thought the intention with your previous patch was to switch from "give me revision X" to "give me a revision at least as new as X".  Shouldn't the latter work even if X is now stale?  If not, that's a bit sad.

**Comment by caseydavenport** [comment]
> I thought the intention with your previous patch was to switch from "give me revision X" to "give me a revision at least as new as X".

@fasaxc Yeah, it was, but I guess that gets thrown out when the API server doesn't actually recognize the revision that we give it (or at least that's what the linked issue suggests).

> Did we make any knock-on changes based on the assumption that we'll always get "at least as new as X" results?

I don't think so. I seem to recall that the previous fix was mostly done as a means to reduce the burden on the API server rather than a change in semantics on our side, although my memory is pretty bad :sweat_smile:

**Comment by fasaxc** [comment]
Dug out the [old PR](https://github.com/projectcalico/libcalico-go/pull/1484).  Looks like using "not older than" was my suggestion :sweat_smile: .  My reasoning was this:

* Before switching to `"0"`, we were always doing consistent reads of the latest state.
* That means that, implicitly, we'd always get "not older than" semantics, since the consistent read _must_ include everything we'd already seen.
* Without "not older than" you can get a stale read that results in undoing some changes that you've already applied.  That is confusing (for the user) and makes the syncer harder to reason about downstream (for us).
* Best avoided so we don't have to do the work of auditing code against that problem.

However, here we are, introducing the possibility of a stale list in a fairly hard to reach corner case.  I think we'd need a combination of:

- Multiple API servers
- One API server "behind"
- One API server "ahead"
- Ahead API server does an etcd compaction, triggering us to lose our watch.
- We connect to the Ahead server and try a list, it fails due to being stale.
- We connect to the Behind server and try a list, it succeeds but we get stale data.

I had a read of the code that I thought might be impacted and I _think_ that case will be handled OK:

- watcher cache itself does a mark and sweep and doesn't look at/numerically compare revisions so it should correctly handle "going back in time"
- Enteprise EGW function that could see an "undeletion" of an EGW should just ignore it.
- I couldn't think of any other areas that might get confused (beyond seeing some resources revert to old states).

Let's go with this change and maybe plan to do "watch bookmarks"?  I think those are supposed to solve the problem of watches that don't get any events across a compaction requiring a re-list.  That would make this problem even less likely (and reduce load on API server even more).

**Review by fasaxc — APPROVED** [review]

**Comment by caseydavenport** [comment]
Before merging this I want to have a go at adding some additional testing around this scenario, though.

**Pull request merged**
