### PR TITLE
Name all required Calico packages in upgrade instructions

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by DaveLangridge** [comment]
I think we should say use `yum update` and review the list of packages that are going to be upgraded. If you don't want all these, then quit out and either list all the packages you want (e.g. all those from the calico repository - that apears in the output), or use  ` yum --disablerepo="*" --enablerepo="calico" update`

Also need  'service neutron-server restart` at the end of the RHEL upgrade compute node section.

**Comment by DaveLangridge** [comment]
LGTM

**Comment by neiljerram** [comment]
@DaveLangridge this has passed checks now, so could be merged...

**Comment by DaveLangridge** [comment]
Merged. OK to delete branch?

**Comment by neiljerram** [comment]
Yes, fine to delete.

**Pull request merged**
