### PR TITLE
Fix whitespace on releases page

### PR DESCRIPTION
**Pull request by lmm**
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by neiljerram** [comment]
@lmm Can you point to the page and problem that you're fixing here?

**Comment by tmjd** [comment]
I believe this is intended to fix https://docs.projectcalico.org/releases, the extra space between the v3.12 link and v3.11.
I wish netlify was building previews here, that would make checking on this much easier.

**Comment by neiljerram** [comment]
@tmjd Thanks.  I see the current HTML source is like this:
```
  <li><a href="/master" data-proofer-ignore="">nightly</a></li>
  <li>
    <p><a href="https://docs.projectcalico.org/v3.12">v3.12</a></p>
  </li>
  <li><a href="/v3.11" data-proofer-ignore="">v3.11</a></li>
  <li><a href="/v3.10" data-proofer-ignore="">v3.10</a></li>
```
So at the HTML level, it looks like we want to lose the `<p>` and `</p>`.  And presumably Markdown generates those based on the source whitespace.

**Comment by tmjd** [comment]
I tried running `make serve` with this branch and that didn't result in a populated `releases` page so I'm not sure how to verify this.

**Comment by neiljerram** [comment]
@lmm @tmjd 
I _think_ this is good, because I think it will net down like this:
```
- [title (latest)](/)
- [nightly](/master){%- for version in site.data.archives -%}{%- if version.first -%}{%- for v in version["legacy"] %}
- [{{ v }}](/{{ v }}){%- endfor -%}{% else %}
- [{{ version }}]({{ site.url }}/{{ version }}){%- endif -%}{%- endfor %}
```

But I'm not completely sure about `{%- endfor -%}{% else %}` eats the following newline or not.  (We need it *not* to.)  It depends if the `-%}` eats whitespace until the next tag, or until the next non-whitespace output.  https://shopify.github.io/liquid/basics/whitespace/ says "to strip whitespace from the left or right side of a rendered tag," which isn't completely clear to me.

I think we need either to preview this, or to change the whole page to a sane whitespace design, which I think is to have every tag begin with `{%- ` and to end with ` %}.  In other words, always eat whitespace before, never eat whitespace after.

**Comment by lmm** [comment]
> change the whole page to a sane whitespace design

@neiljerram that is better, thanks.

@tmjd to preview this with `make serve`, I temporarily edit `_config.yml` by making `archive: true`

**Pull request merged**
