### PR TITLE
Misc typo fixes - III

### PR DESCRIPTION
**Pull request by Akasurde**
## Description

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Review by neiljerram — APPROVED** [review]
LGTM, thanks @Akasurde

**Comment by caseydavenport** [comment]
Test failures look to be known flakes, so merging. Thank you!

**Comment by Akasurde** [comment]
@neiljerram @caseydavenport Thanks for the review and merge.

**Pull request merged**
