### PR TITLE
minor doc fix

### PR DESCRIPTION
**Pull request by surajnarwade**
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by tmjd** [comment]
Thanks for the fix. We need to apply this to the v3.0 and v2.6 _includes also. Could you do that @surajnarwade ?

**Comment by surajnarwade** [comment]
@tmjd , yeah sure

**Comment by surajnarwade** [comment]
@tmjd , I have updated v3.0 and v2.6 as well

**Comment by tmjd** [comment]
LGTM
@ozdanborne PTAL

**Pull request merged**
