### PR TITLE
Add envxx support to MTUIfacePattern

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
The below warning message appears in `calico-node` pod of k8s cluster on `ppc64le` architecture.

```[WARNING][83] felix/int_dataplane.go 967: Failed to auto-detect host MTU - no interfaces matched the MTU interface pattern. To use auto-MTU, set mtuIfacePattern to match your host's interfaces```

The mtuIfacePattern has default pattern `^((en|wl|ww|sl|ib)[Pcopsx].*|(eth|wlan|wwan).*)`, which does not match the network inteface in `ppc64le`.
The `ppc64le` architecture has the host interfaces starting with env. eg: env2, env3 etc..
Hence the default pattern has to include v in [Pcopsx].

Also in `calico/reference/felix/configuration.md` the default value of mtuIfacePattern is not mentioned properly. The symbol | had to be escaped and \<code\> \</code\> was included.

### CODE REVIEW

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag PTAL

**Comment by Rajalakshmi-Girish** [comment]
@caseydavenport Can you PTAL?

**Comment by Rajalakshmi-Girish** [comment]
@fasaxc @lwr20 Can you please take a look at this PR?

**Comment by ctauchen** [comment]
@Rajalakshmi-Girish 

Hi! We've moved the Calico documentation to new repo: https://github.com/tigera/docs.

Can you resubmit your changes there?

**Comment by Rajalakshmi-Girish** [comment]
> Can you resubmit your changes there?

Hope the change to `felix/config/config_params.go` must go into this repo itself.
I shall submit doc changes to https://github.com/tigera/docs. too.

But seems the changes to docs in this repo are also needed! @ctauchen Can you please clarify?

**Comment by caseydavenport** [comment]
@ctauchen looks like there are still some docs left in this repository that didn't' get removed? We should remove those

**Comment by ctauchen** [comment]
Confusing indeed. @caseydavenport The PR I've had up to remove those last remnants is here: https://github.com/projectcalico/calico/pull/7408.

**Comment by ctauchen** [comment]
@Rajalakshmi-Girish I hope you'll forgive us for the confusion here. We migrated all the documentation to tigera/docs. But it appears that a few files, including those you want to edit, remained. This was an error. The only place you need to update documentation is tigera/docs.

**Comment by caseydavenport** [comment]
I've merged the other PR, so we can remove the docs changes from this one and just leave the code.

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by Rajalakshmi-Girish** [comment]
I messed up while trying to rebase :(
Hence closing this. Have raised https://github.com/projectcalico/calico/pull/7523.
@caseydavenport Can you please look at the new PR?

**Pull request closed without merging**
