### PR TITLE
Add typha metrics config with Operator

### PR DESCRIPTION
**Pull request by tmjd**
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]

**Comment by tmjd** [comment]
I removed the addition of `---` from the start of the the installation crd. I thought it was causing a problem with an openshift test I was trying to do. In the end I don't think it fixed the issue as I had another setting that actually fixed it but removing the addition works so I'm not adding it back.

**Comment by neiljerram** [comment]
@tmjd @caseydavenport Isn't the general plan here to stop the operator using env vars, so that FelixConfiguration can be used for this kind of thing?  Why not get on with that instead of adding fields to operator resources?

**Comment by tmjd** [comment]
Yes @neiljerram that is the plan but currently there is no option for configuration of this metrics port for typha besides setting the environment variable. We don't have a TyphaConfiguration like we do for felix.

Is there a datastore config option for this that we missed?

**Comment by neiljerram** [comment]
@tmjd Gotcha, I missed that this is TyphaConfiguration and not FelixConfiguration.  I'm not aware of any datastore config that has been missed here.

**Pull request merged**
