### PR TITLE
Makefile: Build improvments. Incremental by default

### PR DESCRIPTION
**Pull request by tomdee**

### CODE REVIEW

**Comment by caseydavenport** [comment]
Hm, I know I've had trouble with incremental builds in the past.

From my experience, incremental builds don't catch changes to the `_data` directory (e.g changes to navbars)

@djosborne might know more.

**Comment by neiljerram** [comment]
What difference does `--incremental` make?  If I run `make serve`, I _already_ see that the site is updated when I change any source.

**Comment by caseydavenport** [comment]
@neiljerram it makes it faster.  Rather than rebuilding the entire site (which takes 15+ seconds on my machine) it just rebuilds the changes (takes ~1s on my machine)

**Comment by neiljerram** [comment]
Ah, OK, I didn't realise that what appeared to be incremental was actually a complete rebuild!

**Comment by djosborne** [comment]
@neiljerram With incremental builds on, changes to sidebar layout or `docwithnav` will still build the whole site. But changes to a single markdown file will only take a fraction of a second

**Pull request merged**
