### PR TITLE
Fix up the port requirements table

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

- Typha port is only required when Typha is enabled
- Group Calico networking options together
- Make the intro text more explicit

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by emanic** [comment]
@caseydavenport It is overall very nice except perhaps some minute details, but is there any way we can merge targetPort PR first and then rebase this one off of master LMK

**Comment by caseydavenport** [comment]
@emanic rebased

**Comment by caseydavenport** [comment]
> Calico networking, cluster of more than 50 nodes

> In fact, Typha is required in the configuration that I had described.....

Nah, this isn't true. It's not required, and it's only _recommended_ when using Kubernetes API datastore which wasn't explained in the table and I don't think it should be - we can't say "When using Calico on a cluster of over 50 nodes and configured to use the kubernetes api datastore" whenever we really mean "When typha is enabled". It's not accurate and way too verbose.

**Comment by caseydavenport** [comment]
> This seems fine but I prefer to use consistent terminology vis a vis Typha

Agreed, but that terminology should be "When typha is enabled".

**Comment by emanic** [comment]
Let us just merge it and we can discuss more later then

**Comment by caseydavenport** [comment]
> Let us just merge it and we can discuss more later then

I'd rather discuss first and get agreement. I also have a few other changes I've realized I'd like to make.

**Pull request merged**
