### PR TITLE
Update operator version to latest release branch

### PR DESCRIPTION
**Pull request by lmm**
## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by lmm** [comment]
@tmjd or should this be master instead?

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 1094ec587cbecbe5cdc0f8a59462d0132da3c64e

https://deploy-preview-3799--calico.netlify.app

**Comment by tmjd** [comment]
@lmm at this point I think this could be master because the next release of operator for Calico will be off the next Enterprise operator release which has not been branched yet and will be off of operator master. I hope that makes sense.

**Comment by lmm** [comment]
Thanks @tmjd , I've changed the version to master

**Pull request merged**
