### PR TITLE
Fix CNI version to be v0.3.1

### PR DESCRIPTION
**Pull request by caseydavenport**
- [ ] Tests
- [ ] Documentation
- [ ] Release note

```release-note
Use CNI spec version 0.3.1
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit bf5038039e0c0679387799a65adec8b3aefa355d

https://deploy-preview-2882--calico.netlify.com

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 6776b132f6ee4a81602bbc2798a079f8abe91116

https://deploy-preview-2882--calico.netlify.com

**Comment by seh** [comment]
Does this fix #2886?

**Comment by caseydavenport** [comment]
I think #2886 is actually a result of us tagging a release from a commit _before_ this change. 

I think we should close #2886 though - we'll cut a new patch release in the near future which updates the release archive with the new manifests.

**Pull request merged**
