### PR TITLE
Improve diags if there are no profiles attached to an endpoint.

### LINKED ISSUE #718: Logging for felix unclear if vm has no security groups attached.
If a vm has no security groups associated with it, then felix does not add it and deletes the chain associated with it, giving the below log.  Rather than just saying the Endpoint is unready, it would be more helpful if it explained why it was unready i.e. no profile_ids / no security group ids are associated with this vm.

2015-07-08 16:04:39,468 [INFO][21479/227] calico.felix.endpoint 337: Endpoint<IPv6,id=EndpointId<e9798859-0afe-4cc6-a084-ad6d01f643c1>,iface=tape9798859-0a> became unready.

### PR DESCRIPTION
**Pull request by fasaxc**
Fixes #718.

TODO:
* [x] Fix
* [ ] UTs

### CODE REVIEW

**Comment by matthewdupre** [comment]
test this please

**Comment by matthewdupre** [comment]
test this please

**Comment by matthewdupre** [comment]
test this please

**Comment by matthewdupre** [comment]
Sorry about the comments / builds - was testing a new job to build docs for PRs

**Comment by fasaxc** [comment]
_missing_deps removed under #822 so we should just get the endpoint chain written as normal but with no profiles in it.

**Pull request closed without merging**
