### PR TITLE
Fix up etcd manifest env var population

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description

Fixes https://github.com/projectcalico/calico/issues/1576

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by tomdee** [comment]
Deploy preview for *calico* ready!

Built with commit ea6e1c7195ac80b6fb8edeb7087467b57d8d802a

https://deploy-preview-2188--calico.netlify.com

**Comment by tomdee** [comment]
Deploy preview for *calico* ready!

Built with commit 8a36715225f1d2d506b70bf14ff0f5a62f351461

https://deploy-preview-2188--calico.netlify.com

**Comment by ApsOps** [comment]
@caseydavenport Thanks for this!

Could you please tell why is this a DaemonSet anyway? It should either be a deployment or it should have the correct clustering flags.

This is breaking for a multi-master cluster since the etcd pods don't form a cluster and calico nodes talk to a random etcd pod (all of which have their own version of data).

I'll be happy to open a PR if you could please confirm if there's a reason for choosing a daemonset :)

**Comment by caseydavenport** [comment]
> Could you please tell why is this a DaemonSet anyway? It should either be a deployment or it should have the correct clustering flags.

Yes, it's wrong for this to be a DaemonSet. There was a reason for it once... but it was very long ago and I cant seem to recall it, so maybe we should just swap it to a Deployment. We'll need to release note it since it might surprise users on upgrade. 

Ultimately, I'd much prefer to use something like etcd-operator, but that project currently is missing some features which would make it work for us.

**Pull request merged**
