### PR TITLE
[release-v3.15] cherry-pick: Duplicate entry for FELIX_WIREGUARDMTU

### PR DESCRIPTION
**Pull request by hakman**
## Description

Original PR: #3725 (cherry picked from commit 9120bc8ded49e68a23dfc0165b360985ff5d93fe)

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by hakman** [comment]
CC: @fasaxc

**Comment by fasaxc** [comment]
CI doesn't seem to be running against this PR.  I'm digging into that...

**Comment by hakman** [comment]
If you want I can close / reopen to see if it fixes itself.

**Comment by fasaxc** [comment]
I've raised a support ticket, probably best to wait until they get back to me.

**Comment by hakman** [comment]
ACK

**Comment by caseydavenport** [comment]
@hakman I'm sorry, I didn't see this PR!

I just merged a pick for this here: https://github.com/projectcalico/calico/pull/3755

**Comment by hakman** [comment]
I don't mind. Thanks for taking care of it. :)

**Pull request closed without merging**
