### PR TITLE
Clean up canonical stragglers

### PR DESCRIPTION
**Pull request by emanic**
## Description

- Adds some canonical URLs which were accidentally omitted previously
- Deletes supported_platforms from master which has been removed from v3.0 

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by ozdanborne** [comment]
Is there a place I can read up on what's the model for this canonical linking? I see don't see any pattern as to which version a page is supposed to link to.

Maybe add something to CONTRIBUTING_DOCS.md that explains what you're supposed to set `canonical_url` on any given page.

**Comment by emanic** [comment]
Oh hi @ozdanborne thanks for taking a look. I have added some information about the canonical_url links in CONTRIBUTING_DOCS.md. That's in a separate PR here https://github.com/projectcalico/calico/pull/1211. However, at a high level, no one should have to set these canonical links manually unless they are deleting or renaming a page. So this PR represents just some stragglers from a one-time effort. Let me know if you have any other questions.

**Comment by emanic** [comment]
Actually, if they are adding a new page to directories other than the latest (such as master), then they do need to add a canonical_url...I will update the other PR with this information.

**Comment by emanic** [comment]
Thanks @ozdanborne

**Pull request merged**
