### PR TITLE
Update felix docs to use calicoctl instead of etcd.

### LINKED ISSUE #655: Felix configuration docs talk about etcd, not calicoctl
http://docs.projectcalico.org/v2.1/reference/felix/configuration talks about using etcd to set options at the bottom.  This is an implementation detail: it should mention `calicoctl config set` instead.

### PR DESCRIPTION
**Pull request by fasaxc**
@matthewdupre Is this what you had in mind?

Fixes #655

### CODE REVIEW

**Comment by tomdee** [comment]
ping @matthewdupre

**Comment by djosborne** [comment]
ping @matthewdupre

**Comment by fasaxc** [comment]
Matt's on vacation, caould @tomdee or @djosborne take a look?

**Comment by caseydavenport** [comment]
@fasaxc could you update the PR to include the v2.2 documentation, and then let's merge this.

And just for fun... ping @matthewdupre.

**Comment by caseydavenport** [comment]
This also needs to be applied to v2.3 now.

**Pull request merged**
