### PR TITLE
Fix handling unicode kubeconfig file

### PR DESCRIPTION
**Pull request by song-jiang**
## Description

This PR fixes https://github.com/projectcalico/calico/issues/6829 where `findstr` can't handle unicode kubeconfig file.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by coutinhop — APPROVED** [review]
LGTM

**Comment by mweibel** [comment]
@song-jiang are you sure this PR fixes #6829? I'm not sure but #6923 sounds more relevant to this fix. Would be great if you could double check. Thanks!

**Comment by song-jiang** [comment]
@mweibel Thanks for looking into this. My PR did take the `possible solution` (see below) from https://github.com/projectcalico/calico/issues/6923 and incorporated it into Calico installation script. 
```
revert back to approach from older versions of the script with proper powershell approach:
$server=(Get-ChildItem $KubeConfigPath | Select-String https).Line
```

**Comment by mweibel** [comment]
yes, so #6923 is fixed but #6829 not, or am I misunderstanding something?

**Comment by song-jiang** [comment]
@mweibel Oh. I see your point. Sorry I've put down wrong issue number for this PR. Get it fixed now.

**Comment by mweibel** [comment]
awesome, thanks! No worries at all, happens :)

**Pull request merged**
