### PR TITLE
Fixes #1036 . Corrects routing from old version

### LINKED ISSUE #1036: Jump to current release link goes to landing page instead of specific doc
We put a banner at the top of old docs releases to redirect people to the latest docs, for example: https://docs.projectcalico.org/v2.1/getting-started/kubernetes/.  Clicking the link in the banner sends you to the landing page for the new release of the docs, which is disorienting.  It'd be much more useful to send the user to the corresponding page in the docs (if there is such a page).

## Expected Behavior
Banner jumps to new version of same document.

## Current Behavior
Banner jumps to landing page.

## Possible Solution
- Redirect to same path, with new version inserted
- Handle 404 case gracefully with a nice landing page

## Context
This tripped up a user today; he'd reached the 2.0 docs via Google so he didn't know how to navigate back to the doc he was reading at the new version level.

### PR DESCRIPTION
**Pull request by rakrup**
## Description
This is a bug fix - fixing issue #1036 .
This bug fixes routing related issues from old version of doc to latest version.
Tested on dev machine using make serve and make htmlproofer targets
Documentation gets fixed with this PR.

### CODE REVIEW

**Comment by rakrup** [comment]
I have made the changes now so that instead of going to latest and then getting redirected it will go to the explicit version. However , the htmlproofer is still failing due to : 
- The test fails for the pages that are there in the old version but are not there in the new version.
- Cases where URL has been tweaked in newer version [ex. mesos/vagrant is now named as mesos/vagrant-centos and hence obviously failing]

These would be case to case and failures are for around 7-8 links. Please advice if you want it to be handled differently. Would love to learn !

**Comment by rakrup** [comment]
Any help on this folks ? any suggestions on what should be the right way to fix this ?
Looking forward get this fixed.

**Comment by ozdanborne** [comment]
Ah this is awesome, thank you so much for adding this @rakrup , very elegant solution to a really painful problem we have right now.

As for fixing the broken links - Ideally we'd check if the doc exists before linking to it, and if it doesn't exist, just link to the intro page of the release. Though I'm not sure if that's technically possible with jekyll. @mikestowe tried something similar with the following code:

```
{% assign page_exists = site.html_pages | where: "path", page_url %}
```
But `site.html_pages` is an enormous object and piping it to `where` takes so long github pages builds time out.

Maybe we edit the link after rendering using JS?

**Comment by rakrup** [comment]
@ozdanborne Thanks for the appreciation. ☺️
I was also looking for a way in Jekyll to first check the link for 404 and then redirect based on the output; didn't quite get any leads in that direction.
I haven't worked with javascript, but let me take some time so see how we can fix this issue.

**Comment by rakrup** [comment]
This fix does fix the problem for majority of the links. currently less then 5 links have problems after this. Can we merge this one till we look at fix for the other issue @ozdanborne ? I might need some help/pointers for the fix

**Comment by ozdanborne** [comment]
@rakrup Unfortunately I can't let this go in as merging it would break master builds for all PRs.

However, @emanic is working on a PR right now which identifies pages that don't have a previous link with a page variable called `no_canonical`: https://github.com/projectcalico/calico/pull/1203/files

I'd imagine the following logic could work:
```
if no_canonical != true
  redirect to previous version
else
  redirect to docs home
```

**Comment by caseydavenport** [comment]
@ozdanborne I believe the no_canonical PR has been merged now - can we proceed with this PR?

**Comment by ozdanborne** [comment]
I managed to implement something using the new `canonical_url` which takes into account if the doc exists: #1799

Closing.

**Pull request closed without merging**
