### PR TITLE
Docker-only development environment

### PR DESCRIPTION
**Pull request by sedefsavas**
## Description
This PR adds a development environment to calico that requires only docker. It is an alternative method to vagrant development environment. It builds calico in a container and then spin up a kind cluster and install the new calico images.

fixes <https://github.com/projectcalico/calico/issues/3079>

## Related issues/PRs
<https://github.com/projectcalico/calico/issues/2929>

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 0fca32d56d027b9f638709fa600626b7cf4cf642

https://deploy-preview-3129--calico.netlify.com

**Comment by jayunit100** [comment]
Yayyyyyy!!!!1 so we can delete the vagrant one now ???

**Comment by fasaxc** [comment]
@jayunit100 @sedefsavas I think you were the only users of the vagrant set-up, so why don't you nix that in the same PR so we don't get a proliferation of dev envs.

**Comment by caseydavenport** [comment]
Yep, agreed. Let's drop the vagrant setup now.

**Comment by caseydavenport** [comment]
@jayunit100 @sedefsavas ping - I think we should remove the vagrant env in this PR as well.

**Comment by caseydavenport** [comment]
Not seeing any activity on this one - going to close for now. Please re-open when you have a moment to remove the old vagrant bits.

**Pull request closed without merging**
