### PR TITLE
Disable IPv6 support for Kubernetes hosted installs.

### PR DESCRIPTION
**Pull request by caseydavenport**
As discussed here https://github.com/projectcalico/calico-containers/issues/1242#event-844153070

### CODE REVIEW

**Comment by marun** [comment]
I still get the error reported in https://github.com/projectcalico/calico-containers/issues/1242 with this change applied.  When looking at the logs, calico.felix.config reports reading values for ``FELIX_ETCD_*`` and ``FELIX_HOSTNAME`` from the environment, but no indication that ``FELIX_IPV6SUPPORT`` is being read.

**Comment by fasaxc** [comment]
Still some digging to do?

**Comment by caseydavenport** [comment]
@fasaxc yeah, still some digging to do.  I'm not going to have time for this guy until after kubecon, unfortunately.

Will re-visit then.

**Comment by matthewdupre** [comment]
Possibly missing some environment variable pass-through code in calico-containers?

**Comment by caseydavenport** [comment]
@matthewdupre I think that's probably it.

We probably just need to add a line here: https://github.com/projectcalico/calico-containers/blob/master/calico_node/filesystem/etc/service/available/felix/run

**Comment by marun** [comment]
bump

**Comment by caseydavenport** [comment]
I'm a little bit rusty on how environment variables are passed around inside calico/node, but I _do_ know that I've recently seen Felix respect the `FELIX_LOGSEVERITYSCREEN` environment variable.

If it isn't respecting the `FELIX_IPV6SUPPORT` variable then maybe that is something going wrong in Felix?

**Comment by caseydavenport** [comment]
When I run this on `latest` I see the following:

```
2016-12-10 05:34:33.544 [INFO][89] env_var_loader.go 40: Found felix environment variable: "ipv6support"="false"
```

So it's definitely finding it.  I ran this on a system that supports IPv6 though, so won't say it works until I can re-test against one without IPv6 support.

**Comment by caseydavenport** [comment]
Looks like we might have been hitting this: https://github.com/projectcalico/felix/issues/1319.

The iptables driver wasn't respecting the plugin, which explains why the error would still be present with the flag set.

**Comment by caseydavenport** [comment]
That seems to be a fix in the Golang dataplane driver, so maybe not.  @fasaxc any reason to believe that would exist in the python driver as well?

**Comment by caseydavenport** [comment]
I'm starting to question if this is actually the right default behavior for k8s.  

Kubernetes is moving in the direction of IPv6 and in fact some users are using Calico for Pod IPv6 addresses in k8s today.  

We should fix the original issue here https://github.com/projectcalico/calicoctl/issues/1242

**Pull request closed without merging**
