### PR TITLE
Move page about Neutron API to a better location

### LINKED ISSUE #216: reference/advanced/calico-neutron-api in wrong place
http://docs.projectcalico.org/v2.0/reference/advanced/calico-neutron-api

Feels like this doc is in the wrong place.  Maybe it belongs in the getting-started/openstack section?

Or maybe we need orchestrator specific reference sections with FAQ, etc for each?

### PR DESCRIPTION
**Pull request by neiljerram**
Fixes #216

### CODE REVIEW

**Comment by neiljerram** [comment]
Or should I only be changing the v2.0 and master doc here, and leave the v1.5 and v1.6 as is?

**Comment by neiljerram** [comment]
@caseydavenport Please could you review?

**Comment by caseydavenport** [comment]
@neiljerram Yeah, let's just change 2.0 and master.

We don't want to start moving pages around from under people's feet on the old releases :)

**Comment by neiljerram** [comment]
OK, will update in a mo.

**Comment by caseydavenport** [comment]
Other than reverting v1.5 and v1.6, this LGTM.

**Comment by neiljerram** [comment]
OK, I'll revert those bits and then merge without troubling you further - thanks.

**Comment by neiljerram** [comment]
Closed by mistake... Continued in https://github.com/projectcalico/calico/pull/244

**Pull request closed without merging**
