### PR TITLE
fix: ec2 detection not working with imdsv2

### LINKED ISSUE #7969: Windows: EC2 platform detection not working with IMDSv2
When installing calico on windows (on EC2) it doesn't detect the platform type correctly.
[The detection](https://github.com/projectcalico/calico/blob/master/node/windows-packaging/CalicoWindows/libs/calico/calico.psm1#L480C68-L480C99) doesn't handle the IMDSv2 endpoint correctly.

## Expected Behavior
```
Get-PlatformType
ec2
```

## Current Behavior
```
Get-PlatformType
bare-metal
```

## Possible Solution
```
$token = Invoke-RestMethod -Headers @{"X-aws-ec2-metadata-token-ttl-seconds" = "21600"} -Method PUT -Uri http://169.254.169.254/latest/api/token -ErrorAction Ignore
Invoke-RestMethod -Headers @{"X-aws-ec2-metadata-token" = $token} -uri http://169.254.169.254/latest/meta-data/local-hostname -ErrorAction Ignore
```

## Steps to Reproduce (for bugs)
1. Install calico on a windows node
2. The ec2 metadata endpoint will not work afterwards, since the platform type has been detected as `bare-metal` instead of `ec2`

## Context
Manual route fixing required to make the ec2 metadata endpoint work again.

## Your Environment
* Calico version 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.27.4
* Operating System and version: Windows Server Core 2022

### PR DESCRIPTION
**Pull request by davidgiga1993**
## Related issues/PRs

fixes #7969 

## Todos

- [X] Tests Tested in own ec2 windows environment
- [ ] Documentation
- [x] Release note

## Release Note

```release-note
Fixed aws ec2 detection not working with imdsv2 on Calico for Windows.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by lwr20** [comment]
pinging @coutinhop

**Review by coutinhop — APPROVED** [review]
LGTM, thanks @davidgiga1993

**Comment by davidgiga1993** [comment]
@coutinhop Fixed, had the wrong commit email

**Pull request merged**
