### PR TITLE
DOCS-1123: Fixes bad HTML output on Docusaurus site

### PR DESCRIPTION
**Pull request by ctauchen**
https://tigera.atlassian.net/browse/DOCS-1123

Removes a blank line that caused strange output on the migrated docs site.

### CODE REVIEW

**Review by girishshankaran — APPROVED** [review]
lgtm

**Review by girishshankaran — APPROVED** [review]
lgtm

**Comment by ctauchen** [comment]
@bmckercher123 Can you approve this please?

**Review by bmckercher123 — APPROVED** [review]
Approved

**Pull request merged**
