### PR TITLE
Replace Google Search with Algolia

### PR DESCRIPTION
**Pull request by rymarchikbot**
## Description

Requested by @alexvarsh

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 19086c59624320dcdc76a993b8700e36e42b5730

https://deploy-preview-2354--calico.netlify.com

**Comment by matthewdupre** [comment]
I was able to test this fine just by hitting back?  I think to use site.baseurl we'd have to configure Algolia to crawl the preview, which would take time, possibly cost money and be a hassle.

**Comment by caseydavenport** [comment]
It seems to work well for me, but I think the padding around the bar itself isn't quite as nice looking as the previous - it looks very cramped to me.

**Comment by matthewdupre** [comment]
@rymarchikbot @alexvarsh could you please add a bit more space around the search bar (Casey's comment), and I also think "Search the documentation" is better than "Search in the documentation".  A follow up PR is fine though, this has been around for way too long so I'm going to merge.

@alexvarsh reviewed the js/css and is happy with it.

**Pull request merged**
