### PR TITLE
API Version changes for searching

### PR DESCRIPTION
**Pull request by alexvarsh**
enable sitemap

### CODE REVIEW

**Comment by ozdanborne** [comment]
The reason `sitemap` is enabled for all pages except for the latest release is that we only want google to index the latest release. Otherwise, google results get filled with our older releases. We've noticed a considerable improvement in our SEO since we started doing this

@alexvarsh One option might be to separately generate an additional sitemap.xml for  search to use

**Comment by emanic** [comment]
@alexvarsh Since we started including a sitemap.xml that only includes the latest directory, we have seen major improvements in our Google search results. So, as @ozdanborne notes, we should keep the sitemap.xml file as is. I think Google will crawl any sitemap.xml file that we include, so I am not sure what benefit multiple sitemap.xml files might offer, but I'll let @ozdanborne advise further on this idea. Thanks...

**Comment by ozdanborne** [comment]
After discussing with @alexvarsh  and @lxpollitt , we've decided to host two sitemaps: one that includes the full site, and one that just includes the latest release. Then we'll point each tool at the required sitemap. Both tools allow a configurable location for their sitemap. 

We've decided to let the internal site search tool use the sitemap automatically generated by the jekyll-seo gem since it changes more frequently and is arguably more important. We'll point Google at the new `sitemap-static.xml`. 

There is follow-up work needed to define a process during the release whereby we update `sitemap-static.xml`

**Comment by ozdanborne** [comment]
@alexvarsh FYI I pushed a commit to this PR which added the new `sitemap-latest.xml`

**Pull request closed without merging**
