### PR TITLE
Automated cherry pick of #4749: Updated styles and table rows

### PR DESCRIPTION
**Pull request by bcreane**
Cherry pick of #4749 on release-v3.19.

#4749: Updated styles and table rows

### CODE REVIEW

**Comment by bcreane** [comment]
@bmckercher123 can you verify the change on the preview: https://app.netlify.com/sites/calico/deploys/60f1b4fca63f910007186534. I'll merge once you give the PR your 👍

**Comment by bmckercher123** [comment]
Approved

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Review by lmm — APPROVED** [review]

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
