### PR TITLE
Move git-hooks to central location

### PR DESCRIPTION
**Pull request by Akasurde**
## Description

After merging all repo to one repo, git-hooks directory needs to be centrally located.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by lmm** [comment]
Thanks @Akasurde! I took a quick look and I think maybe we want the top-level folder to be named `.git-hooks`.

**Comment by Akasurde** [comment]
> Thanks @Akasurde! I took a quick look and I think maybe we want the top-level folder to be named `.git-hooks`.

OK. I will do the needful.

**Comment by lmm** [comment]
I can't seem to add a review on the moved files so I'll just add comments.
I think these lines need to be prefixed with `felix/`:
https://github.com/projectcalico/calico/blob/1417e46a3cbf7fce31773830e50c904c8f26d0d8/git-hooks/files-to-skip#L1-L2

**Comment by lmm** [comment]
@Akasurde I think you need to update this line too: https://github.com/projectcalico/calico/blob/e3da9d7f5a7002479f228f7968767d5665129d2f/install-git-hooks#L6

**Comment by fasaxc** [comment]
I think install-git-hooks is called from the makefiles.  If you move it then the makefiles need to be updated?

**Comment by caseydavenport** [comment]
Closing due to inactivity

**Pull request closed without merging**
