### PR TITLE
Update RPM dependencies to include newly-built packages.

### PR DESCRIPTION
**Pull request by fasaxc**
Add additional dependencies that were missing.

### CODE REVIEW

**Comment by fasaxc** [comment]
Paul, this is an updated version of your PR.  I found there were some other missing deps and the python-posix-spawn package came out as just posix-spawn.  There doesn't seem to be a way to change the name of the package generated by bdist_rpm.

**Comment by Symmetric** [comment]
If we change the name to 'python-posix-spawn' in that package's setup.py, then the generated RPM will use that name; I made that change locally but didn't have time to put up a PR for it. I could add that change to https://github.com/Symmetric/python-posix-spawn/commit/40d54951b4958dd853cd643075339f62a043ade9 if you want?

**Comment by fasaxc** [comment]
Not sure I want to make that change; we'd have to update PyPI and calico's python deps too.

**Comment by Symmetric** [comment]
LGTM

**Pull request merged**
