### PR TITLE
Added hint to service advertisement documentation 

### PR DESCRIPTION
**Pull request by rgarcia89**
## Todos

- [ ] Tests
- [x] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 745d61ce827a869abff940a80031edae9816e5ef

https://deploy-preview-2762--calico.netlify.com

**Comment by caseydavenport** [comment]
@rgarcia89 is there a related issue that this addresses? I don't think it should be required to add the service CIDR as an IP pool.

Were you seeing issues without this?

**Comment by rgarcia89** [comment]
@caseydavenport I posted the issue on slack (https://calicousers.slack.com/archives/C0BCA117T/p1564478489068600?thread_ts=1564478489.068600&cid=C0BCA117T). Without adding the network to the ippool the route was pointing to eth0 instead of tunl0. 

Am I missing something?

**Comment by caseydavenport** [comment]
Ah, I see. In the slack post you mention multiple clusters? I think that might be relevant here. I don't think adding an IP pool is correct for many use-cases of this feature.

I think we should discuss your use-case a bit more before changing the docs, since I think the docs have a different setup in mind (single cluster, advertising into the network via ToR, Calico not programming any routes to the linux routing table at all).

**Comment by rgarcia89** [comment]
Sure let me explain you my use case:

So we do have multiple clusters which run Calico as CNI. Every cluster represents its own AS. Our goal was it to make pods of every cluster be able to cross communicate with each other. Therefore, we set the BGP neighbors, add the pod CIDR of the remote cluster and modified the bird config to keep the next hop. So far everything works like planed. Thanks to the bird config modification the routes are directly pointing to the node that holds the /26 sub-range of the pod CIDR.

As next step, we wanted to make the service address CIDR available for the cross cluster communication as well. So I added the CALICO_ADVERTISE_CLUSTER_IPS variable to calico-typha manifest and applied it to our two clusters. With that I started to see the service CIDR route on the nodes of the remote cluster. No comes the problem - they were pointing to the default gateway and using the wrong interface - eth0. Since we want to hold the traffic within the clusters we need this route to use tunl0. This was achieved by adding the CIDR of the remote cluster to the calico ippool.

I hope this makes our use case understandable

**Comment by caseydavenport** [comment]
Sorry for the silence on this one. I think that this PR, as it currently stands, it's the right formulation. Many users of this feature won't want an IP pool that covers their service range, so this would be the wrong suggestion for them.

I could imaging a separate guide which covers how to configure your scenario, though.

**Pull request closed without merging**
