### PR TITLE
Remove dead links

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by djosborne** [comment]
Same links exist in `master/` too

**Comment by caseydavenport** [comment]
@djosborne done

**Comment by djosborne** [comment]
Glad to see the dead links fixed, so going to merge.

@caseydavenport What is the plan going forward for directing users on Bare Metal Kubernetes installs with Calico? If we want to, we could restore this links to the old docs in the git history of kubernetes.github.io

**Comment by caseydavenport** [comment]
@djosborne we have two options there.

- Re-instate the removed docs with something up-to-date.
- Update our existing documentation to make it clear that the docs apply to both bare-metal and public cloud environments.

I think we def want to do the second, and then potentially the first down the road.

**Pull request merged**
