### PR TITLE
change default endpoint to host action to ACCEPT

### PR DESCRIPTION
**Pull request by gunjan5**
this was missing in `/master`

### CODE REVIEW

**Comment by caseydavenport** [comment]
Could you update the etcd and kubeadm manifests as well?

**Comment by gunjan5** [comment]
@caseydavenport done! (although I don't fully understand why this is needed for etcd backend)

**Comment by caseydavenport** [comment]
@gunjan5 we shouldn't be changing the v1.5 and v1.6 manifests here, just the ones in v2.0

v2.0/standard
v2.0/kubeadm
v2.0/etcdless

> although I don't fully understand why this is needed for etcd backend

The datastore should change this behavior.  I don't fully understand why you saw it with one and not the other :)

Perhaps you had configuration in etcd somehow?  This value can be configured in etcd.

**Comment by caseydavenport** [comment]
@gunjan5 pong, back to you

**Comment by gunjan5** [comment]
@caseydavenport:
> we shouldn't be changing the v1.5 and v1.6 manifests here, just the ones in v2.0

I looked at Felix code and both v1.5 and v1.6 had that flag, so I thought we should have the same behavior, no?

>> although I don't fully understand why this is needed for etcd backend

> The datastore should change this behavior. I don't fully understand why you saw it with one and not the other :)
> Perhaps you had configuration in etcd somehow? This value can be configured in etcd.

Nope, didn't even touch etcd. And I tried a bunch of times on fresh installs.

**Comment by caseydavenport** [comment]
> I looked at Felix code and both v1.5 and v1.6 had that flag, so I thought we should have the same behavior, no?

Was mostly concerned about changing behavior under people's feet.  I usually don't like the idea of changing a manifest from a previous release.  In this particular case, I suppose it's acceptable, but I'd like to limit the amount of changes we make to v1.5, v1.6, etc because users are relying on consistent behavior from past releases.

**Comment by gunjan5** [comment]
@caseydavenport done. I wasn't sure what you meant by `v2.0/standard`, but I've changed the systemd file for v2.0 and master.

**Comment by caseydavenport** [comment]
@gunjan5 you're missing v2.0/k8s-backend

**Comment by gunjan5** [comment]
@caseydavenport that change was already merged I think when you cut 2.0.2: https://github.com/projectcalico/calico/blob/master/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend/calico.yaml#L77

**Comment by caseydavenport** [comment]
Hmm.. not sure what's up with the build.

**Comment by gunjan5** [comment]
@caseydavenport Rebased, and the CI works now :)

**Pull request merged**
