### PR TITLE
Git managed versions

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by neiljerram** [comment]
@djosborne I wonder what you might think about this suggestion.  The idea is to allow us to use normal Git/GitHub process to manage doc for different Calico versions - in corresponding Git branches - instead of having subtrees per version in a single 'master' branch.  Then

- we could do things like cherry-picking or merging changes between branches (as appropriate)
- we can use nice UIs like gitk and GitHub to easily see differences between branches
- it becomes more trivial than it is currently to create a doc set for a new version - mostly it's just creating a new Git branch.

What I've suggested will coexist with the existing versions - so we wouldn't need immediately to move those into Git branches.  We could try this approach out for the next version and see how we like it, and then decide whether to consolidate on it, or trash the idea.

WDYT?

**Comment by djosborne** [comment]
@neiljerram I understand your approach. Those three bullet points would be nice gains. 

I think the cost is that - each time we make a change to a doc in a version branch, we would need to rerun `get_git_branch_versions.sh` on the master branch to pick up the new changes. Right?

**Comment by neiljerram** [comment]
@djosborne Yes, that's right.  Specifically I think there are two cases:

- When a change is committed to the GitHub repo, I assume there is an automated process that runs to update docs.projectcalico.org.  That process would need to add a `get_git_branch_versions.sh` call.

- When a developer is making a change in branch 'vX.Y', for a Git-managed version, and wants to see what it looks like, they have two options: (1) just look at the 'master' version doc shown by their local webserver, and understand that that will actually be the 'vX.Y' doc once it is published; or (2) do `get_git_branch_versions.sh` before `make`.

Also a couple of other things occurred to me that might make this a bad idea, so in the spirit of full disclosure...

- It makes it harder for a developer to search for and replace something across all versions.  The search part is OK, because they just need `get_git_branch_versions.sh` first, but the replace part is harder because (at least so far) the design doesn't include any path back from the flat (i.e. current) representation to Git branches.

- It _might_ make it harder for us to vary the structure of the repository in future.  (Possibly this is just a particular case of the previous point, when the changes include moving directories around.)

Thoughts?  Perhaps this all adds up to too much new complexity...

**Comment by djosborne** [comment]
@neiljerram 
> I assume there is an automated process that runs to update docs.projectcalico.org
As it stands, the Github Pages service entirely handles this process for us. It's one of the nice things about this setup, that whatever we check into master is magically hosted for us. But the drawback is we have 0 control over it, and can't customize it the way you are suggesting.

I'm still thinking this through. But I believe that the three points you raised as pro's can all be achieved on the current set up with a bit of Git know-how. Which makes me think we're just making something less difficult by introducing more processes and "inside knowledge".

**Comment by neiljerram** [comment]
Thanks for thinking about this, @djosborne.  I don't fully understand yet what you have in mind with your second paragraph, but it sounds like the first paragraph pretty much rules this change out.

**Comment by djosborne** [comment]
@neiljerram Closing for now. I'll leave it up to you reopen and drive this post 2.0 if you believe this would improve calico docs

**Pull request closed without merging**
