### PR TITLE
Delete redundance package for apiserver storage code.

### PR DESCRIPTION
**Pull request by yanggangtony**
## Description
Delete redundance package for apiserver storage code.

```release-note
None
```

### CODE REVIEW

**Review by caseydavenport — APPROVED** [review]

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Comment by yanggangtony** [comment]
@caseydavenport 
this pr is so long time  , would it be closed or merged then?

**Comment by caseydavenport** [comment]
@yanggangtony sorry for losing this one. It seems fine to merge, so long as it passes tests.

**Comment by yanggangtony** [comment]
Thanks.

**Pull request merged**
