### PR TITLE
Update docs for keepOriginalNextHop in bgppeer resource

### PR DESCRIPTION
**Pull request by gunboe**
## Description
Adjusts are made to describe the new feature `keepOriginalNextHop` in `bgppeers` resource.

## Related issues/PRs

https://github.com/projectcalico/libcalico-go/pull/1266
https://github.com/projectcalico/confd/pull/339

## Todos

- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 800844b7a819e79ecabd5236ee4689033f2fa5f8

https://deploy-preview-3867--calico.netlify.app

**Comment by gunboe** [comment]
> https://deploy-preview-3867--calico.netlify.app

@caseydavenport  I have visited that link but changes in [800844b](https://github.com/projectcalico/calico/commit/800844b7a819e79ecabd5236ee4689033f2fa5f8) are not displayed. Is there something wrong or did i do something stupid?

And the Milestone here is different to the PR https://github.com/projectcalico/confd/pull/339, I think it would be 3.16.0, didn't you?

**Comment by neiljerram** [comment]
@gunboe See https://deploy-preview-3867--calico.netlify.app/master/reference/resources/bgppeer.  (You have to add "master/" into those deploy preview URLs.)

I or @caseydavenport will fix up the milestone, but the most important thing is to rebase and merge the confd PR.

**Comment by neiljerram** [comment]
@gunboe confd is merged and milestone updated now.

I added Release Note text in the top comment above.  Please could you review, and feel free to improve!

**Pull request merged**
