### PR TITLE
fix to separate crd

### PR DESCRIPTION
**Pull request by stamm**
## Description

fix to separate crd while creating

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 0878df9bdf74b687bd4d69e8a149bf5fcb9ffef3

https://deploy-preview-2496--calico.netlify.com

**Comment by neiljerram** [comment]
@stamm I'm wondering though if these files are still used in our v3.6 and master installs.  Did you have to make these changes because of hitting a specific problem?

**Comment by stamm** [comment]
@neiljerram yes, crd ippools hasn't been created, and I think bgppeers hasn't been created, but I update from calico 3.2 and bgppeers was already exists

**Comment by ozdanborne** [comment]
@stamm I accidentally created `_includes/v3.6/charts/calico/templates/kdd-crds.yaml` last week. I just merged a PR to remove it (#2497 ). Can you rebase / resolve conflicts by removing your adjustment to that file? Thanks!

**Comment by stamm** [comment]
@ozdanborne done!

**Pull request merged**
