### PR TITLE
[release-v3.28] cherry-pick: Add setting to enable wireguard NAPI threading (#9260)

### PR DESCRIPTION
**Pull request by jrcichra**
## Description

This adds a new setting to enable wireguard NAPI threading on the wireguard interfaces. NAPI threading can be used with wireguard to help increase maximum packets-per-second by distributing the tunnel's load from one core to many cores via a NAPI kernel thread.

This option is off by default and can be configured via the FelixConfiguration the same way wireguard can be toggled on and off.

Tested on a bare metal Kubernetes cluster. NAPI threading is enabled on the second pass of ensureLink, once the interface is up. I get operation not permitted on the first run before the up|peertopeer flags are set, which is why I have a flag guard.

This affects calico-node the most when it's configuring the wireguard interface. All other components are reconciling the new FelixConfiguration parameter.

## Related issues/PRs

Original: https://github.com/projectcalico/calico/pull/9260

## Todos

- [ ] Tests
- [ ] Documentation
- [x] Release note

## Release Note

```release-note
Add setting to enable wireguard NAPI threading
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Comment by jrcichra** [comment]
I'll take a look at the two CI errors tomorrow and iterate locally.

**Comment by jrcichra** [comment]
Got a pass with:
```
make fv GINKGO_FOCUS="the Wireguard device should have napi threading set correctly" GINKGO_ARGS="-ginkgo.progress -ginkgo.v -ginkgo.failFast"
```

```
Ran 6 of 886 Specs in 118.302 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 880 Skipped
```

I ran a `make generate` and got an updated output from calicoctl crds.go.

**Review by mazdakn — APPROVED** [review]
LGTM

**Pull request merged**
