### PR TITLE
Itechart/update instantsearch

### PR DESCRIPTION
**Pull request by anton-klokau**
Updated instantsearch library to v4. Also added some fixed to search container. Pagination will not be shown if there will only one page of search results and popover will not be hidden on click inside of it.

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 843248bfa99759762e7a628b62eb2b90a37bc63c

https://deploy-preview-3554--calico.netlify.app

**Comment by lmm** [comment]
This looks nicer than the current search and it seems to work the same or maybe faster (hard to tell). One thing I do notice is that search highlighting is leaving a noticeable gap to the right of the word. For example, in the below search it looks like "OpenSt  ack" (notice the extra spacing). Is that something that's simple to fix?

image

**Comment by lmm** [comment]
As a comparison, here is what the current search results rendering looks like: 
image

**Comment by anton-klokau** [comment]
Hey, @lmm 
Didn't noticed this white space
Instantsearch isn't guilty for it, this extra space came from bootstrap styles, so it was simple to fix it

**Pull request merged**
