### PR TITLE
Update styles for header

### PR DESCRIPTION
**Pull request by Stanislav-Galchynski**
## Description

This PR provides style updates for the header according to mockups.

### CODE REVIEW

**Review by alexeymagdich-tigera — APPROVED** [review]
Looks good to me.

**Comment by bmckercher123** [comment]
Please do not merge this PR yet. We are working on a docs epic for both CE and OS docs site to replace "Releases" with a new widget for Version that should be used for both OS and CE. So even if you get signoff on this PR, our changes should go in first so you can then drop "Releases" from top nav. OS and CE docs sites are tightly coupled on the backend, and we cannot diverge without assessing risk to stability of both docs sites.

**Comment by frozenprocess** [comment]
@Stanislav-Galchynski I noticed something and wanted to double check it, If you resize the page lower than 1023px sidebar navbar & `toggle nav` button  appears in the top but it will not dissapear whe you click the `toggle nav` button.
In iPad this leads to a `div` presentation leak where stuff are on top of eachother.
image

**Suggestion** Since in mobile devices there is a limited amount of space, it would be awesome to make one of the navbars disspear while user scrolls the page to read the content.

**Comment by ozdanborne** [comment]
@Stanislav-Galchynski these changes as you've implemented them will automatically get carried over into the Enterprise docs site when we perform our frequent merge from OS => Private, which is undesirable.

Would you be able to implement this in such a way that the old sidebar and new sidebar are checked into source code alongside one another, and we conditionally load them using a flag in `_config.yml` and a snippet that does something like:
```
{{ if site.open_source }}
{% include "open_source_navbar.html" %}
{{ else }}
{% include "enterprise_navbar.html %}
{{ endif }}
```

Otherwise, we'll need someone to take responsibility for reverting the change during the OS => private merge, and dealing will all subsequent merge conflicts that arise from future OS => private merges.

The only other option I can see is if we allow the changes to be merged to private and then modify once they land to create an enterprise version of this new navbar. If we do that, it should reduce the number of conflicts that come out of that merge. But I need your team's commitment that they'll be taken care of between the merge and the next enterprise release.

**Review by ozdanborne — APPROVED** [review]
Perfect! Thanks @Stanislav-Galchynski

**Pull request merged**
