### PR TITLE
Cherrypick-non-cluster-host

### PR DESCRIPTION
**Pull request by bmckercher123**
## Cherrypick to 3.19

https://github.com/projectcalico/calico/pull/4666

### CODE REVIEW

**Review by bcreane — APPROVED** [review]
I reviewed the preview and it looks good.

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and delete the branch after I've merged it.

**Comment by marvin-tigera** [comment]
I'm sorry but I failed delete the branch after merging the pull request.

**Pull request merged**
