### PR TITLE
Adding -bird-live option to the liveness check

### PR DESCRIPTION
**Pull request by asincu**
## Description
Adding a check for bird and confd as part of the liveness check

## Related issues/PRs
fixes projectcalico/calico#2889
https://github.com/projectcalico/node/pull/369

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note
```
Adding -bird-live/-bird6-live option to check for bird, bird6 and conf as part of the liveness probe.
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 4599f7ef2aaaf0dfd91117cccd7cd90cdd214a91

https://deploy-preview-3011--calico.netlify.com

**Comment by caseydavenport** [comment]
These will go live as soon as we merge, so we need to make the non-master changes _after_ we cut the patch releases.

It's a sad consequence of how we do manifest generation today.

**Comment by caseydavenport** [comment]
@asincu could you pull out the `master` changes into their own PR?

**Comment by asincu** [comment]
@caseydavenport I will open a new PR with the changes for 3.8, 3.9 and 3.10.

**Pull request merged**
