### PR TITLE
Remove repository line from config

### PR DESCRIPTION
**Pull request by tomdee**
- [ ] Tests
- [ ] Documentation
- [ ] Release note

```release-note
None required
```

It's used by anything

### CODE REVIEW

**Comment by tomdee** [comment]
Deploy preview for *calico* ready!

Built with commit 381774f3d4806dce3b5e103f32f36784d9449bc0

https://deploy-preview-2195--calico.netlify.com

**Comment by ozdanborne** [comment]
For the record, the `github-pages` gem (which the github-pages docker image included) had some plugin for autopopulating some info on the repo. When run locally, it needed `repository` or it would fail.

If it still builds locally with `make` when removed then we're good to remove it.

**Comment by caseydavenport** [comment]
@tomdee can we merge this?

**Comment by tomdee** [comment]
It leads to this error when building
```
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
```

I don't think we actually want this GH metadata thing anymore, but we should open a different PR to remove it.

**Pull request closed without merging**
