### PR TITLE
Add backoff to watchercache resync loop.

### LINKED ISSUE #5215: calico/typha is reconnecting without any back-off mechanism
We observed that when the kubernetes api server is not available,
`calico/typha` is trying to reconnect to the kubernetes server
without any back-off mechanism and it can easily reach 1k connection attempts/s.

Would it be possible to throttle the retries to about 100/s or 10/s?

We are concerned about a possible overload issue on our reverse proxy
in the network path, which is shared by several kubernetes api servers.

## Expected Behavior

The reconnect attempts are throttled.

## Current Behavior

image

Calico/typha maintains a high reconnect rate indefinitely.

## Possible Solution

Throttle the reconnect attempts.

## Steps to Reproduce (for bugs)

1. Monitor the connection establishment attempts by the `calico/typha` pod
2. Stop the kubernetes api server

## Context

We are introducing a feature where the network path to the hosted api servers
share a load balancer and a few reverse proxies,
and we are concerned that this thundering herd behavior might lead to a DDoS attack.

Related issue: https://github.com/projectcalico/felix/issues/324#issuecomment-111108710

## Your Environment

* And/Or, `calico/typha` container version (if running Typha in a container): `v3.13.5`
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): `1.20.2`

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

Set a minimum interval (500ms) between resyncs on all code paths.

## Related issues/PRs

fixes #5215

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Add backoff to Kubernetes watch loops to avoid tight looping in certain failure scenarios.
```

### CODE REVIEW

**Comment by fasaxc** [comment]
WDYK, there were a bunch of tests for the existing throttling behaviour...

**Comment by caseydavenport** [comment]
@fasaxc is this one you're planning to pick up again?

**Comment by fasaxc** [comment]
@caseydavenport yup, today as it happens :grin:

**Review by robbrockbank — APPROVED** [review]
LGTM

**Pull request merged**
