### PR TITLE
enable direct customization of the FelixConfiguration

### PR DESCRIPTION
**Pull request by PauloGDPeixoto**
## Description

New feature: Include an option to directly customize the FelixConfiguration.

## Related issues/PRs

#7735

### CODE REVIEW

**Comment by lwr20** [comment]
Have you tried this out?  I can think of some reasons why this won't work, but would love to be proved wrong.

**Comment by PauloGDPeixoto** [comment]
> Have you tried this out? I can think of some reasons why this won't work, but would love to be proved wrong.

Yes I have, and it works. This is basically duplicating what is done for the Installation, why wouldn't it work?

**Comment by lwr20** [comment]
FelixConfiguration is a `projectcalico.org/v3` object.  That will only be applyable once the calico-apiserver is running - while that's down (e.g. in the case of installing calico on a fresh cluster), applying that object will fail.

**Comment by PauloGDPeixoto** [comment]
You're absolutely correct, I was under the impression that I had created a cluster with this code in place, but in fact, I didn't.

**Comment by PauloGDPeixoto** [comment]
Awesome, thanks for the feedback and good luck working that out!

**Pull request closed without merging**
