### PR TITLE
Fix typo in NAT section on about-networking.md

### PR DESCRIPTION
**Pull request by lanandra**
## Description

Found typo or mistyped word on about-networking.md line 141  
Below is git diff  on the mistyped section  

        -private source IP address of tha packet to the router's own public IP address before forwarding it on to the internet.
        +private source IP address of the packet to the router's own public IP address before forwarding it on to the internet.  

previously it was typed tha packet, proposed to change to the packet so that the sentence does not have typo

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Review by lmm — APPROVED** [review]
Thanks @lanandra !

**Comment by lanandra** [comment]
Hi @lmm,

Sure. You are welcome

**Comment by lanandra** [comment]
Hi @lmm ,  

I just want to make sure about this commit. I found this commit has been merged to master.  
File about-networking.md also has been changed as if in this commit.  

But when i checked from [Link](https://docs.projectcalico.org/about/about-networking)  
Typo has not been corrected.  

image  

Is there something that i missed ? or that i should do to correct this?

**Comment by caseydavenport** [comment]
@lanandra the master branch isn't used for the live docs - there is a release-v3.18 branch that shows the live docs.

This change will show up in v3.19, when we cut a new branch from master.

**Comment by lanandra** [comment]
Hi @caseydavenport , 

thanks for you explanation. seems like i've misread some guide so that i am not aware about that branching for live docs

**Pull request merged**
