### PR TITLE
Add cniVersion in CNI config manifests and examples

### PR DESCRIPTION
**Pull request by gunjan5**
Fixes https://github.com/projectcalico/calico/issues/610

### CODE REVIEW

**Comment by gunjan5** [comment]
Ok to merge only for master after https://github.com/projectcalico/cni-plugin/pull/302 is merged

**Comment by djosborne** [comment]
Just wondering, why can't this be merged yet? Shouldn't our CNI plugin just ignore unexpected fields?

**Comment by gunjan5** [comment]
i guess it can be, I was thinking if we want to use 0.3.0 but seems like 0.3.1 is the right one, wanted to get the CNI PR looked at first (this should be part of that)

**Comment by djosborne** [comment]
Sounds good. I was just trying to wrap my head over what the upgrade path might be for users, i.e. if having / not having this in the json would cause issues before / after the upgrade

**Comment by gunjan5** [comment]
Calico CNI should be able to handle both cases with or without cniVersion in the json. Calico CNI should be flexible now so it can handle no cniVersion or any of the older versions if requested by the orchestrator

**Comment by tomdee** [comment]
What is the k8s behaviour with this version? Will it throw an error because it doesn't understand this new version yet? In which case, should we continue defaulting to the old version?

**Comment by tomdee** [comment]
And shouldn't we wait to bump the cniVersion until we have a release of our CNI plugin that actually support this CNI version? i.e. the two should be bumped in lockstep?

**Comment by gunjan5** [comment]
@tomdee these changes are in master docs and the images we use in this doc are `:master` and the CNI code change is in `calico/cni:master` so it should be ok. As per k8s, it can still continue to work even if it requests for an older version or no version string at all, it will get the result in the format it understands for that version

**Comment by tomdee** [comment]
OK, SGTM

**Comment by gunjan5** [comment]
@tomdee is the SGTL for the comment or for the PR? Ok to megre?

**Pull request merged**
