### PR TITLE
Update docs calico version from v3.8.0 to v3.13.2

### PR DESCRIPTION
**Pull request by xieyanker**
## Description

The latest calico version has updated to v3.13.2, but the docs still use v3.8.0

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Deploy preview for *calico* ready!

Built with commit 6e7753e54ce77266b27e4ea60b58947bd347413d

https://deploy-preview-3423--calico.netlify.com

**Comment by lmm** [comment]
Thanks for the PR @xieyanker. The "hard way" docs were based on Calico v3.8. My guess is that updating that "hard way" tutorial would require changes other than bumping the image versions. Have you by chance run through the tutorial to see if it still works with v3.13?

**Comment by xieyanker** [comment]
@lmm Thanks for your reply. In fact, I didn't try to deploy calico v3.13 by "hard way". I just found the version is a bit old while I reading the documentation. You can close this PR if the "hard way" only supports v3.8.  But I still think it is necessary to update the documentation to the latest version, we should perfect it if it's not compatible with v3.13 now.

**Comment by lmm** [comment]
Thanks @xieyanker, I'm going to close this PR for now. But I did raise an [issue](https://github.com/projectcalico/calico/issues/3446) so we can track this. I think you're right, we shouldn't let the tutorial version get too far behind 👍

**Pull request closed without merging**
