### PR TITLE
DOCS-991: syntax fix in calicoctl ipam command

### PR DESCRIPTION
**Pull request by girishshankaran**
## Description

 https://tigera.atlassian.net/browse/DOCS-991?atlOrigin=eyJpIjoiN2FmNDExMzQxNWFkNGRjNTg5ZTE5MTg2Zjg0YThjYTYiLCJwIjoiaiJ9

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
TBD
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

**Review by ctauchen — APPROVED** [review]
lgtm

**Review by caseydavenport — APPROVED** [review]

**Comment by mgleung** [comment]
@girishshankaran this looks ready to go. I think all we need is for you to sign the CLA

**Comment by ctauchen** [comment]
@girishshankaran If this CLA thing is still blocking you? Could try a fresh PR with the new creds.

**Comment by girishshankaran** [comment]
@mgleung I signed the CLA multiple times but not accepting.
@ctauchen Yes, will create a fresh PR.

**Pull request closed without merging**
