### PR TITLE
Restore route reflector tests

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by neiljerram** [comment]
This should pass CI once https://github.com/projectcalico/confd/pull/71 and https://github.com/projectcalico/routereflector/pull/3 have merged.

**Comment by emanic** [comment]
@neiljerram You can rebase off the latest master to resolve the htmlproofer errors.

**Comment by neiljerram** [comment]
Thanks @robbrockbank and @caseydavenport .

I'm wondering though, if I need to add something to _data/versions.yml to reference a particular version of calico/routereflector - which I guess also means that it becomes a release artefact - and machinery in the routereflector repo to push tagged images to dockerhub and quay.  Currently that machinery is missing and the ST process here just pulls calico/routereflector:latest.  (How is that working....?)

**Comment by neiljerram** [comment]
So specifically, I'd now propose:

- first, to review and merge https://github.com/projectcalico/routereflector/pull/3 - to which I've just added a release machinery commit

- then to release that as calico/routereflector v0.5.0

- then to review and merge this PR, which now references calico/routereflector v0.5.0.

WDYT?

**Comment by neiljerram** [comment]
(Just rebased.)

Also I previously just released calico/routereflector v0.5.0, would expect the CI now to pass on this PR...

**Pull request merged**
