### PR TITLE
Handle interface renames by simulating a delete/re-add.

### LINKED ISSUE #1075: Felix doesn't handle new interface name for endpoint
I tried updating an endpoint with a new host-side veth name and I see the following log repeated:

```
calico.felix.endpoint 292: Update on interface cali8077ce8b707 that we do not care about
```

We do care about this interface, Felix!

In k8s it is possible for a container to be restarted with the same identifiers, meaning a new veth is created and then the endpoint is updated to reference that veth.  I'm not seeing the route programmed by Felix in this case.

Haven't had a chance to dig into the code in detail yet, but it looks like we're not tracking the change `endpoint_id_by_iface_name` properly.

@fasaxc any thoughts?

### PR DESCRIPTION
**Pull request by fasaxc**
Fixes #1075.

### CODE REVIEW

**Comment by fasaxc** [comment]
@caseydavenport I'm not set up to repro #1075, please can you test that this actually fixes the problem you were seeing?

**Comment by caseydavenport** [comment]
I will test this today.

**Comment by caseydavenport** [comment]
I've re-tested and confirmed that this is working now.  Hooray!

**Comment by robbrockbank** [comment]
and the change LGTM.

 FTR, I had one question about whether the force_resync flag should be false when deleting the endpoint - but chatting to Shaun that is not necessary.

**Comment by robbrockbank** [comment]
Merging

**Pull request merged**
