### PR TITLE
Fixed broken docker link

### LINKED ISSUE #1158: Link on route reflector page is not rendering as link
https://docs.projectcalico.org/v2.6/usage/routereflector/calico-routereflector#starting-up-the-route-reflector
I see `[Docker v1.6][docker]` which I believe should be rendered to a link.

## Expected Behavior
Link is displayed

## Current Behavior
Unrendered text is displayed

## Possible Solution
Fix it

## Steps to Reproduce (for bugs)
1. View https://docs.projectcalico.org/v2.6/usage/routereflector/calico-routereflector#starting-up-the-route-reflector

## Context
I was looking for something else and noticed that.

## Your Environment
* Calico version: v2.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s

### PR DESCRIPTION
**Pull request by surajnarwade**
Fixes #1158

### CODE REVIEW

**Comment by tmjd** [comment]
Thank you for the update, could you also apply this change in the v3.0 and master sections too.

**Comment by surajnarwade** [comment]
@tmjd fixed here https://github.com/projectcalico/calico/pull/1483

**Comment by tmjd** [comment]
Thanks, I was hoping for it to be added to this PR, if you're comfortable doing that it would be great if you could add those changes here instead of a separate PR. Generally it is nice to have the same changes going into the different versioned sections in the same PR.

If you're not comfortable adding those updates here please just say so.

**Comment by tmjd** [comment]
Well since that other PR was merged I guess this is good to go.
@emanic PTAL

**Comment by emanic** [comment]
Oh OK, missed this one. Thanks @tmjd and @surajnarwade !

**Pull request merged**
